//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_fpagam
    {
        public string a_fpagamstamp { get; set; }
        public decimal Codigo { get; set; }
        public string descricao { get; set; }
        public bool Tipo { get; set; }
        public bool ObgTitulo { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool Numer { get; set; }
        public bool pos { get; set; }
    }
}
