//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_usr
    {
        public string a_usrstamp { get; set; }
        public decimal numero { get; set; }
        public string nome { get; set; }
        public string login { get; set; }
        public bool activo { get; set; }
        public bool usradmin { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool Programa { get; set; }
        public bool Fornecedores { get; set; }
        public bool Tabelas { get; set; }
        public bool Relatorio { get; set; }
        public bool posapenas { get; set; }
        public bool noexcel { get; set; }
        public bool nopreco { get; set; }
        public bool userap { get; set; }
        public bool usercl { get; set; }
        public bool userint { get; set; }
        public bool userfnc { get; set; }
        public bool usrtz { get; set; }
        public bool usrrlt { get; set; }
        public bool usrtab { get; set; }
        public string email { get; set; }
        public bool naodepart { get; set; }
        public string pw { get; set; }
    }
}
