//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class acessos
    {
        public string Descricao { get; set; }
        public bool ver { get; set; }
        public bool intro { get; set; }
        public bool altera { get; set; }
        public bool apaga { get; set; }
        public bool anula { get; set; }
        public bool imprimir { get; set; }
        public bool superv { get; set; }
        public bool ctrldel { get; set; }
        public bool ctrlalter { get; set; }
        public string acessosstamp { get; set; }
        public string a_usrmodulostamp { get; set; }
        public string a_usrstamp { get; set; }
        public string ecran { get; set; }
        public decimal tipo { get; set; }
        public string sigla { get; set; }
        public decimal numdoc { get; set; }
        public decimal numrlt { get; set; }
        public decimal nordem { get; set; }
        public decimal codmodulo { get; set; }
        public decimal codmenu { get; set; }
        public decimal ordem { get; set; }
        public bool headgroup { get; set; }
        public bool activo { get; set; }
        public bool painel { get; set; }
    
        public virtual a_usrmodulo a_usrmodulo { get; set; }
    }
}
