//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcosterrasEntities : DbContext
    {
        public AcosterrasEntities()
            : base("name=AcosterrasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pedesc> pedescs { get; set; }
        public virtual DbSet<peemp> peemps { get; set; }
        public virtual DbSet<peempcc> peempccs { get; set; }
        public virtual DbSet<peempl> peempls { get; set; }
        public virtual DbSet<pesub> pesubs { get; set; }
        public virtual DbSet<pjpe> pjpes { get; set; }
        public virtual DbSet<Prc> Prcs { get; set; }
        public virtual DbSet<Prcdesc> Prcdescs { get; set; }
        public virtual DbSet<Prcemp> Prcemps { get; set; }
        public virtual DbSet<PRCEXTRA> PRCEXTRAs { get; set; }
        public virtual DbSet<Prcsub> Prcsubs { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<prodarm> prodarms { get; set; }
        public virtual DbSet<profiss> profisses { get; set; }
        public virtual DbSet<pjst> pjsts { get; set; }
        public virtual DbSet<pjvt> pjvts { get; set; }
        public virtual DbSet<vt> vt { get; set; }
        public virtual DbSet<vtcfg> vtcfg { get; set; }
        public virtual DbSet<vtconsumo> vtconsumo { get; set; }
        public virtual DbSet<vtcorreias> vtcorreias { get; set; }
        public virtual DbSet<vtfiltros> vtfiltros { get; set; }
        public virtual DbSet<vtman> vtman { get; set; }
        public virtual DbSet<vtmedpneus> vtmedpneus { get; set; }
        public virtual DbSet<vtoleos> vtoleos { get; set; }
        public virtual DbSet<vtoutros> vtoutros { get; set; }
        public virtual DbSet<vtpneus> vtpneus { get; set; }
    }
}
