//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class apparam
    {
        public string apparamstamp { get; set; }
        public string conta { get; set; }
        public string descricao { get; set; }
        public decimal tsaldo { get; set; }
        public string cd1 { get; set; }
        public string cd2 { get; set; }
        public string cd3 { get; set; }
        public string cd4 { get; set; }
        public string cd5 { get; set; }
        public string cd6 { get; set; }
        public string cd7 { get; set; }
        public string cd8 { get; set; }
        public string cd9 { get; set; }
        public string cc1 { get; set; }
        public string cc2 { get; set; }
        public string cc3 { get; set; }
        public string cc4 { get; set; }
        public string cc5 { get; set; }
        public string cc6 { get; set; }
        public string cc7 { get; set; }
        public string cc8 { get; set; }
        public string cc9 { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string ivarec { get; set; }
        public string ivaant { get; set; }
        public string ivapag { get; set; }
        public string origem { get; set; }
    }
}
