//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixa
    {
        public string Caixastamp { get; set; }
        public decimal numero { get; set; }
        public decimal inicial { get; set; }
        public System.DateTime Data { get; set; }
        public decimal codtz { get; set; }
        public string contatesoura { get; set; }
        public bool Fechado { get; set; }
        public string obs { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public System.DateTime dhorafecho { get; set; }
        public decimal posto { get; set; }
    }
}
