//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class cc
    {
        public string ccstamp { get; set; }
        public string origem { get; set; }
        public string oristamp { get; set; }
        public decimal nrdoc { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime vencim { get; set; }
        public decimal debito { get; set; }
        public decimal debitom { get; set; }
        public decimal debitof { get; set; }
        public decimal debitofm { get; set; }
        public decimal credito { get; set; }
        public decimal creditom { get; set; }
        public decimal creditof { get; set; }
        public decimal creditofm { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string documento { get; set; }
        public string Moeda { get; set; }
        public decimal saldo { get; set; }
        public decimal codmov { get; set; }
        public string Factstamp { get; set; }
        public string rclstamp { get; set; }
        public string rdstamp { get; set; }
        public string ccusto { get; set; }
        public string numinterno { get; set; }
        public decimal estabno { get; set; }
        public string estabnome { get; set; }
    
        public virtual Fact Fact { get; set; }
        public virtual RCL RCL { get; set; }
        public virtual rd rd { get; set; }
    }
}
