//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dc()
        {
            this.dcli = new HashSet<dcli>();
        }
    
        public string dcstamp { get; set; }
        public decimal docno { get; set; }
        public string docnome { get; set; }
        public string abrv { get; set; }
        public bool pedeval { get; set; }
        public bool arredonda { get; set; }
        public string olcodigo { get; set; }
        public bool nvaimapa { get; set; }
        public string oldesc { get; set; }
        public bool lancaol { get; set; }
        public bool naolancapla { get; set; }
        public bool oltrfa { get; set; }
        public bool introol { get; set; }
        public bool ollinhas { get; set; }
        public bool automl { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool apuraiva { get; set; }
        public bool apurares { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dcli> dcli { get; set; }
    }
}
