//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ToolTeste
{

    
    public  class dcli
    {
        [Key]
        public string Dclistamp { get; set; }
        public string dcstamp { get; set; }
        public string conta { get; set; }
        public string rubrica { get; set; }
        public bool deb { get; set; }
        public decimal valor { get; set; }
        public decimal factor { get; set; }
        public decimal evalor { get; set; }
        public decimal lordem { get; set; }
        public bool lbanco { get; set; }
        public string cct { get; set; }
        public string ncusto { get; set; }
        public string oldesc { get; set; }
        public decimal docno { get; set; }
        public string sgrupo { get; set; }
        public string grupo { get; set; }
        public string olcodigo { get; set; }
    
        public virtual Dc dc { get; set; }
    }
}
