//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class di
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public di()
        {
            this.dil = new HashSet<dil>();
            this.dil3 = new HashSet<dil3>();
        }
    
        public string distamp { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public string numinterno { get; set; }
        public decimal numero { get; set; }
        public decimal entidade { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime dataven { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Moeda { get; set; }
        public decimal subtotal { get; set; }
        public decimal perdesc { get; set; }
        public decimal desconto { get; set; }
        public decimal totaliva { get; set; }
        public decimal total { get; set; }
        public decimal Msubtotal { get; set; }
        public decimal Mdesconto { get; set; }
        public decimal Mtotaliva { get; set; }
        public decimal Mtotal { get; set; }
        public decimal codvend { get; set; }
        public string vendedor { get; set; }
        public decimal Cambio { get; set; }
        public bool cambfixo { get; set; }
        public bool impresso { get; set; }
        public string usrimpress { get; set; }
        public System.DateTime impressodh { get; set; }
        public bool Anulado { get; set; }
        public string CodInterno { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool movtz { get; set; }
        public bool movstk { get; set; }
        public bool trf { get; set; }
        public string nomedoc { get; set; }
        public decimal codtz { get; set; }
        public string contatesoura { get; set; }
        public decimal codmovstk { get; set; }
        public string descmovstk { get; set; }
        public string reffornec { get; set; }
        public string ccusto { get; set; }
        public decimal codmovstk2 { get; set; }
        public string descmovstk2 { get; set; }
        public string obs { get; set; }
        public string oristamp { get; set; }
        public bool aprovado { get; set; }
        public decimal codarm { get; set; }
        public string descarm { get; set; }
        public decimal codarm2 { get; set; }
        public string descarm2 { get; set; }
        public decimal codturno { get; set; }
        public string Turno { get; set; }
        public bool clivainc { get; set; }
        public decimal no2 { get; set; }
        public string nome2 { get; set; }
        public bool usaaprova { get; set; }
        public bool fechado { get; set; }
        public string opcao1other { get; set; }
        public decimal pjno { get; set; }
        public string pjstamp { get; set; }
        public bool orc { get; set; }
        public string codcont { get; set; }
        public string codareap { get; set; }
        public string codfin { get; set; }
        public string codlfin { get; set; }
        public Nullable<decimal> tipo { get; set; }
        public Nullable<decimal> no3 { get; set; }
        public string nome3 { get; set; }
        public Nullable<decimal> no4 { get; set; }
        public string nome4 { get; set; }
        public string Mercadoria { get; set; }
        public string tprocess { get; set; }
        public Nullable<decimal> codproc { get; set; }
        public string tservico { get; set; }
        public string Refcl { get; set; }
        public string nrfornec { get; set; }
        public string Fronteira { get; set; }
        public string Terminal { get; set; }
        public string Transp { get; set; }
        public string nrTransp { get; set; }
        public string Destino { get; set; }
        public string Moeda2 { get; set; }
        public Nullable<decimal> Fob { get; set; }
        public Nullable<decimal> Frete { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> ocusto { get; set; }
        public Nullable<decimal> gdiversos { get; set; }
        public Nullable<decimal> Regular { get; set; }
        public Nullable<System.DateTime> dchegada { get; set; }
        public Nullable<decimal> valmin { get; set; }
        public string matrTransp { get; set; }
        public string embarque { get; set; }
        public string volumes { get; set; }
        public string peso { get; set; }
        public Nullable<decimal> CIFMOEDA { get; set; }
        public Nullable<decimal> CIFMT { get; set; }
        public Nullable<decimal> dusequenc { get; set; }
        public Nullable<decimal> duitems { get; set; }
        public string estancia { get; set; }
        public string regime { get; set; }
        public string manifesto { get; set; }
        public string doctransp { get; set; }
        public string nregtransp { get; set; }
        public Nullable<decimal> nvolumes { get; set; }
        public string pembarque { get; set; }
        public string nrcontpag { get; set; }
        public string portdest { get; set; }
        public string ngarant { get; set; }
        public Nullable<decimal> mgarant { get; set; }
        public string sgarant { get; set; }
        public string prdestino { get; set; }
        public string refdeclara { get; set; }
        public Nullable<decimal> metaval { get; set; }
        public string formpagadc { get; set; }
        public string paisdest { get; set; }
        public string nacional { get; set; }
        public string locdescarg { get; set; }
        public string condentreg { get; set; }
        public Nullable<decimal> metpagament { get; set; }
        public Nullable<decimal> fundo { get; set; }
        public Nullable<decimal> prevarmaz { get; set; }
        public string regarmaz { get; set; }
        public string outrinfo { get; set; }
        public string ptransp1 { get; set; }
        public string ptransp2 { get; set; }
        public string ptransp3 { get; set; }
        public string numselo { get; set; }
        public Nullable<decimal> pbruto { get; set; }
        public string outras { get; set; }
        public Nullable<decimal> ntims { get; set; }
        public Nullable<decimal> refcambial { get; set; }
        public Nullable<decimal> refprocur { get; set; }
        public Nullable<decimal> reflicenc { get; set; }
        public string nisencao { get; set; }
        public Nullable<System.DateTime> datisencao { get; set; }
        public string isdireito { get; set; }
        public string isimpcons { get; set; }
        public string issobretx { get; set; }
        public string isiva { get; set; }
        public string blegal { get; set; }
        public string Locmercador { get; set; }
        public string Proprietario { get; set; }
        public string desestancia { get; set; }
        public string desregime { get; set; }
        public string desfrnteira { get; set; }
        public string despembarque { get; set; }
        public string despdestino1 { get; set; }
        public string deslocdescarg { get; set; }
        public string descodentreg { get; set; }
        public string desmetpagam { get; set; }
        public string desfundo { get; set; }
        public string desptrans1 { get; set; }
        public string desptrans2 { get; set; }
        public string desptrans3 { get; set; }
        public string despdestinof { get; set; }
        public string desmeiotransp { get; set; }
        public string desblegal { get; set; }
        public Nullable<decimal> txDireito { get; set; }
        public Nullable<decimal> tximpcons { get; set; }
        public Nullable<decimal> txsobretx { get; set; }
        public Nullable<decimal> txiva { get; set; }
        public Nullable<decimal> tipodu { get; set; }
        public string refinterna { get; set; }
        public Nullable<decimal> tdistrib { get; set; }
        public Nullable<decimal> PDireitos { get; set; }
        public Nullable<decimal> Pimpcons { get; set; }
        public Nullable<decimal> Psobretx { get; set; }
        public Nullable<decimal> Piva { get; set; }
        public Nullable<decimal> zeros { get; set; }
        public string repfinanc { get; set; }
        public string Autorproj { get; set; }
        public string Autorcsta { get; set; }
        public string odisplegal { get; set; }
        public Nullable<decimal> displegal { get; set; }
        public Nullable<decimal> benef { get; set; }
        public string ArtGerais { get; set; }
        public Nullable<decimal> tipoagenc { get; set; }
        public Nullable<decimal> moznumber { get; set; }
        public string tpdescmercad { get; set; }
        public Nullable<decimal> tpcodmercad { get; set; }
        public Nullable<bool> pemb { get; set; }
        public Nullable<bool> adjud { get; set; }
        public Nullable<System.DateTime> datadjud { get; set; }
        public string facc1stamp { get; set; }
        public string facc2stamp { get; set; }
        public Nullable<decimal> ndeclara { get; set; }
        public Nullable<decimal> totpeso { get; set; }
        public Nullable<decimal> totvolume { get; set; }
        public Nullable<decimal> ano { get; set; }
        public Nullable<System.DateTime> dEntrada { get; set; }
        public Nullable<System.DateTime> dCheckin { get; set; }
        public Nullable<System.DateTime> dPagamento { get; set; }
        public Nullable<System.DateTime> dExamin { get; set; }
        public Nullable<System.DateTime> dVerific { get; set; }
        public Nullable<System.DateTime> dPronto { get; set; }
        public Nullable<decimal> cifusd { get; set; }
        public Nullable<decimal> cambiousd { get; set; }
        public Nullable<System.DateTime> DataFecho { get; set; }
        public decimal calcfrete { get; set; }
        public decimal calcseguro { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public bool reserva { get; set; }
        public decimal tipodoc { get; set; }
        public decimal lant { get; set; }
        public decimal lact { get; set; }
        public decimal lreal { get; set; }
        public System.DateTime ldata { get; set; }
        public string tipoentida { get; set; }
        public string zona { get; set; }
        public string ncont { get; set; }
        public decimal codzona { get; set; }
        public string fleitura { get; set; }
        public decimal estabno { get; set; }
        public string estabnome { get; set; }
        public string Morada { get; set; }
        public string Telefone { get; set; }
        public string fax { get; set; }
        public decimal nuit { get; set; }
        public string email { get; set; }
        public decimal optintro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dil> dil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dil3> dil3 { get; set; }
    }
}
