//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class diario
    {
        public string diariostamp { get; set; }
        public decimal dino { get; set; }
        public string descricao { get; set; }
        public decimal docno { get; set; }
        public string docnome { get; set; }
        public decimal dilno { get; set; }
        public decimal deb { get; set; }
        public decimal cre { get; set; }
        public decimal conana { get; set; }
        public decimal confin { get; set; }
        public decimal conord { get; set; }
        public decimal edeb { get; set; }
        public decimal ecre { get; set; }
        public decimal diano { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool defeito { get; set; }
        public bool apura { get; set; }
    }
}
