//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class dil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dil()
        {
            this.mstk = new HashSet<mstk>();
        }
    
        public string dilstamp { get; set; }
        public string distamp { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public string @ref { get; set; }
        public string descricao { get; set; }
        public decimal quant { get; set; }
        public string unidade { get; set; }
        public decimal armazem { get; set; }
        public decimal armazem2 { get; set; }
        public decimal Preco { get; set; }
        public decimal Mpreco { get; set; }
        public string lote { get; set; }
        public decimal tabiva { get; set; }
        public decimal txiva { get; set; }
        public decimal valival { get; set; }
        public decimal mvalival { get; set; }
        public bool ivainc { get; set; }
        public decimal perdesc { get; set; }
        public decimal descontol { get; set; }
        public decimal mdescontol { get; set; }
        public decimal subtotall { get; set; }
        public decimal msubtotall { get; set; }
        public decimal totall { get; set; }
        public decimal mtotall { get; set; }
        public bool status { get; set; }
        public bool usadesign { get; set; }
        public bool servico { get; set; }
        public bool nmovstk { get; set; }
        public string remotestamp { get; set; }
        public bool mpr { get; set; }
        public string oristamp { get; set; }
        public bool Tit { get; set; }
        public decimal ordem { get; set; }
        public bool stkprod { get; set; }
        public string Titstamp { get; set; }
        public bool usaserie { get; set; }
        public string serie { get; set; }
        public Nullable<decimal> contatz { get; set; }
        public Nullable<decimal> codstat { get; set; }
        public bool composto { get; set; }
        public bool usalote { get; set; }
        public decimal pack { get; set; }
        public Nullable<decimal> nlinha { get; set; }
        public string marcnum { get; set; }
        public string acordo { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string moedaf { get; set; }
        public Nullable<decimal> cambiol { get; set; }
        public Nullable<decimal> fobme { get; set; }
        public Nullable<decimal> freteme { get; set; }
        public Nullable<decimal> segurome { get; set; }
        public Nullable<decimal> ocusto { get; set; }
        public Nullable<decimal> cifme { get; set; }
        public Nullable<decimal> cifmt { get; set; }
        public Nullable<decimal> oducifmt { get; set; }
        public string tvolume { get; set; }
        public Nullable<decimal> qttvolumes { get; set; }
        public string classe { get; set; }
        public Nullable<decimal> qttsuplim1 { get; set; }
        public Nullable<decimal> qttsuplim2 { get; set; }
        public string opais { get; set; }
        public string cproced { get; set; }
        public string licenca { get; set; }
        public string anexos { get; set; }
        public string docanter { get; set; }
        public Nullable<decimal> txdireire { get; set; }
        public Nullable<decimal> tximpcons { get; set; }
        public Nullable<decimal> txsobretx { get; set; }
        public Nullable<decimal> vdireire { get; set; }
        public Nullable<decimal> vimpcons { get; set; }
        public Nullable<decimal> viva { get; set; }
        public Nullable<decimal> vsobretx { get; set; }
        public Nullable<decimal> pdireire { get; set; }
        public Nullable<decimal> pimpcons { get; set; }
        public Nullable<decimal> piva { get; set; }
        public Nullable<decimal> psobretx { get; set; }
        public Nullable<decimal> pagina { get; set; }
        public string qualidade { get; set; }
        public System.DateTime lotevalid { get; set; }
        public System.DateTime lotelimft { get; set; }
        public decimal qttmedida { get; set; }
        public decimal totalmedida { get; set; }
        public decimal grupo { get; set; }
        public bool usaperlinha { get; set; }
        public decimal perlinha { get; set; }
        public decimal tipocheck { get; set; }
    
        public virtual di di { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstk> mstk { get; set; }
    }
}
