//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class dil3
    {
        public string cod { get; set; }
        public string descricao { get; set; }
        public string dil3stamp { get; set; }
        public string distamp { get; set; }
        public string intertekstamp { get; set; }
    
        public virtual di di { get; set; }
    }
}
