//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class docmodulo
    {
        public decimal codigo { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> estado { get; set; }
        public string docmodulostamp { get; set; }
        public string rltstamp { get; set; }
        public string tdistamp { get; set; }
        public string tdocstamp { get; set; }
        public string trclstamp { get; set; }
        public string trdstamp { get; set; }
        public string tdocfstamp { get; set; }
        public string tpgfstamp { get; set; }
        public string trdfstamp { get; set; }
    
        public virtual tdi tdi { get; set; }
        public virtual tdocf tdocf { get; set; }
        public virtual tdoc tdoc { get; set; }
        public virtual TRcl TRcl { get; set; }
        public virtual Rlt Rlt { get; set; }
        public virtual Trdf Trdf { get; set; }
        public virtual Trd Trd { get; set; }
        public virtual Tpgf Tpgf { get; set; }
    }
}
