//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public string empresastamp { get; set; }
        public decimal codigo { get; set; }
        public string nome { get; set; }
        public string Morada { get; set; }
        public string Morada2 { get; set; }
        public string sede { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string cell { get; set; }
        public decimal cp { get; set; }
        public string actividade { get; set; }
        public decimal nuit { get; set; }
        public string sigla { get; set; }
        public string MoedaMT { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string infobanc { get; set; }
        public string declarante { get; set; }
        public string refdeclara { get; set; }
        public string logo { get; set; }
        public string webpage { get; set; }
        public string empslogan { get; set; }
        public string actdgi { get; set; }
        public string reparticao { get; set; }
    }
}
