//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ent
    {
        public string Entstamp { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Morada { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string fax { get; set; }
        public decimal cp { get; set; }
        public string email { get; set; }
        public decimal nuit { get; set; }
        public string zona { get; set; }
        public string tipo { get; set; }
        public decimal cod_vend { get; set; }
        public string vendedor { get; set; }
        public string nimpexp { get; set; }
        public decimal perdesc { get; set; }
        public string moeda { get; set; }
        public bool status { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public decimal Tabela { get; set; }
        public System.DateTime Datacl { get; set; }
        public string obs { get; set; }
        public string pais { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string localidade { get; set; }
        public string codpais { get; set; }
        public decimal codarm { get; set; }
        public string descarm { get; set; }
        public bool clivainc { get; set; }
        public decimal codcondpag { get; set; }
        public string descondpag { get; set; }
    }
}
