//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facc()
        {
            this.faccprest = new HashSet<faccprest>();
            this.formasp = new HashSet<formasp>();
            this.Faccl = new HashSet<Faccl>();
            this.fcc = new HashSet<fcc>();
        }
    
        public string faccstamp { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public decimal numero { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime dataven { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Moeda { get; set; }
        public decimal subtotal { get; set; }
        public decimal perdesc { get; set; }
        public decimal desconto { get; set; }
        public decimal totaliva { get; set; }
        public decimal total { get; set; }
        public decimal Msubtotal { get; set; }
        public decimal Mdesconto { get; set; }
        public decimal Mtotaliva { get; set; }
        public decimal Mtotal { get; set; }
        public decimal codvend { get; set; }
        public string vendedor { get; set; }
        public decimal Cambio { get; set; }
        public bool cambfixo { get; set; }
        public bool impresso { get; set; }
        public string usrimpress { get; set; }
        public System.DateTime impressodh { get; set; }
        public bool Anulado { get; set; }
        public string CodInterno { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool movtz { get; set; }
        public bool movstk { get; set; }
        public bool movcc { get; set; }
        public string nomedoc { get; set; }
        public decimal codmovstk { get; set; }
        public string descmovstk { get; set; }
        public decimal codmovcc { get; set; }
        public string descmovcc { get; set; }
        public string numinterno { get; set; }
        public string ccusto { get; set; }
        public string obs { get; set; }
        public string oristamp { get; set; }
        public bool aprovado { get; set; }
        public bool clivainc { get; set; }
        public decimal tipodoc { get; set; }
        public decimal custos { get; set; }
        public bool calc { get; set; }
        public bool integra { get; set; }
        public decimal nodiario { get; set; }
        public string diario { get; set; }
        public decimal ndocCont { get; set; }
        public string descDocCont { get; set; }
        public bool reserva { get; set; }
        public decimal codarm { get; set; }
        public decimal no2 { get; set; }
        public string nome2 { get; set; }
        public string tprocess { get; set; }
        public decimal nrordem { get; set; }
        public decimal nrtimms { get; set; }
        public decimal numreceita { get; set; }
        public string refpagam { get; set; }
        public decimal ndeclara { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faccprest> faccprest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formasp> formasp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faccl> Faccl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fcc> fcc { get; set; }
    }
}
