//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class faccprest
    {
        public string faccpreststamp { get; set; }
        public string faccstamp { get; set; }
        public string descricao { get; set; }
        public System.DateTime data { get; set; }
        public decimal perc { get; set; }
        public decimal valor { get; set; }
        public string obs { get; set; }
        public bool status { get; set; }
    
        public virtual Facc Facc { get; set; }
    }
}
