//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factl()
        {
            this.mstk = new HashSet<mstk>();
        }
    
        public string Factlstamp { get; set; }
        public string Factstamp { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public string @ref { get; set; }
        public string descricao { get; set; }
        public decimal quant { get; set; }
        public string unidade { get; set; }
        public decimal armazem { get; set; }
        public decimal Preco { get; set; }
        public decimal Mpreco { get; set; }
        public decimal tabiva { get; set; }
        public decimal txiva { get; set; }
        public decimal valival { get; set; }
        public decimal mvalival { get; set; }
        public bool ivainc { get; set; }
        public decimal perdesc { get; set; }
        public decimal descontol { get; set; }
        public decimal mdescontol { get; set; }
        public Nullable<decimal> subtotall { get; set; }
        public decimal msubtotall { get; set; }
        public decimal totall { get; set; }
        public Nullable<decimal> mtotall { get; set; }
        public bool status { get; set; }
        public string lote { get; set; }
        public bool usadesign { get; set; }
        public bool servico { get; set; }
        public string oristampl { get; set; }
        public decimal Dispon { get; set; }
        public decimal QttOrig { get; set; }
        public bool nmovstk { get; set; }
        public string remotestamp { get; set; }
        public string oristamp { get; set; }
        public bool Tit { get; set; }
        public decimal ordem { get; set; }
        public bool stkprod { get; set; }
        public bool LineAnulado { get; set; }
        public string Titstamp { get; set; }
        public decimal quant2 { get; set; }
        public decimal quant3 { get; set; }
        public decimal preco2 { get; set; }
        public decimal preco3 { get; set; }
        public Nullable<decimal> contatz { get; set; }
        public decimal pack { get; set; }
        public decimal cpoc { get; set; }
        public decimal cpoo { get; set; }
        public bool usalote { get; set; }
        public bool composto { get; set; }
        public System.DateTime lotevalid { get; set; }
        public System.DateTime lotelimft { get; set; }
        public decimal qttmedida { get; set; }
        public decimal totalmedida { get; set; }
        public decimal grupo { get; set; }
        public bool usaperlinha { get; set; }
        public decimal perlinha { get; set; }
        public decimal tipocheck { get; set; }
        public bool qttdecim { get; set; }
    
        public virtual Fact Fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstk> mstk { get; set; }
    }
}
