//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class factprest
    {
        public string factpreststamp { get; set; }
        public string factstamp { get; set; }
        public string descricao { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Perc { get; set; }
        public decimal Valor { get; set; }
        public string obs { get; set; }
        public bool status { get; set; }
    
        public virtual Fact Fact { get; set; }
    }
}
