//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactPag
    {
        public string descricao { get; set; }
        public decimal Valor { get; set; }
        public decimal Tipo { get; set; }
        public string FactPagstamp { get; set; }
        public string Factstamp { get; set; }
        public bool status { get; set; }
    
        public virtual Fact Fact { get; set; }
    }
}
