//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fact()
        {
            this.Factl = new HashSet<Factl>();
            this.cc = new HashSet<cc>();
            this.formasp = new HashSet<formasp>();
            this.FactPag = new HashSet<FactPag>();
            this.factprest = new HashSet<factprest>();
        }
    
        public string factstamp { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public decimal numero { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime dataven { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Morada { get; set; }
        public string Telefone { get; set; }
        public string fax { get; set; }
        public decimal nuit { get; set; }
        public string email { get; set; }
        public string Moeda { get; set; }
        public decimal subtotal { get; set; }
        public decimal perdesc { get; set; }
        public decimal desconto { get; set; }
        public decimal totaliva { get; set; }
        public decimal total { get; set; }
        public decimal Msubtotal { get; set; }
        public decimal Mdesconto { get; set; }
        public decimal Mtotaliva { get; set; }
        public decimal Mtotal { get; set; }
        public decimal codvend { get; set; }
        public string vendedor { get; set; }
        public decimal Cambio { get; set; }
        public bool cambfixo { get; set; }
        public bool impresso { get; set; }
        public string usrimpress { get; set; }
        public System.DateTime impressodh { get; set; }
        public bool Anulado { get; set; }
        public string CodInterno { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool movtz { get; set; }
        public bool movstk { get; set; }
        public decimal codmovstk { get; set; }
        public bool movcc { get; set; }
        public decimal codmovcc { get; set; }
        public string nomedoc { get; set; }
        public string descmovcc { get; set; }
        public string descmovstk { get; set; }
        public string numinterno { get; set; }
        public string ccusto { get; set; }
        public string obs { get; set; }
        public string oristamp { get; set; }
        public bool aprovado { get; set; }
        public bool adjudicado { get; set; }
        public string origem { get; set; }
        public string coment { get; set; }
        public decimal codarm { get; set; }
        public decimal codturno { get; set; }
        public string Turno { get; set; }
        public decimal Mesa { get; set; }
        public bool Fechada { get; set; }
        public bool isiva { get; set; }
        public bool clivainc { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public decimal tipodoc { get; set; }
        public decimal no2 { get; set; }
        public string nome2 { get; set; }
        public string Morada2 { get; set; }
        public string Localidade2 { get; set; }
        public string codagree { get; set; }
        public string nomecomerc { get; set; }
        public System.DateTime dadjudicado { get; set; }
        public string nadjudicado { get; set; }
        public bool integra { get; set; }
        public decimal noDiario { get; set; }
        public string diario { get; set; }
        public decimal nDocCont { get; set; }
        public string descDocCont { get; set; }
        public bool contabilizado { get; set; }
        public bool reserva { get; set; }
        public decimal lant { get; set; }
        public decimal lact { get; set; }
        public decimal lreal { get; set; }
        public System.DateTime ldata { get; set; }
        public string tipoentida { get; set; }
        public string zona { get; set; }
        public string ncont { get; set; }
        public decimal codzona { get; set; }
        public string fleitura { get; set; }
        public string ncontador { get; set; }
        public string tprocess { get; set; }
        public string nrfornec { get; set; }
        public decimal ndeclara { get; set; }
        public string Refcl { get; set; }
        public string tpdescmercad { get; set; }
        public string volumes { get; set; }
        public decimal cifmoeda { get; set; }
        public decimal cifmt { get; set; }
        public decimal cifusd { get; set; }
        public decimal cambiousd { get; set; }
        public string Moeda2 { get; set; }
        public decimal pjno { get; set; }
        public string pjstamp { get; set; }
        public decimal optintro { get; set; }
        public bool calcfrete { get; set; }
        public bool calcseguro { get; set; }
        public decimal fob { get; set; }
        public decimal frete { get; set; }
        public decimal seguro { get; set; }
        public decimal ocusto { get; set; }
        public decimal estabno { get; set; }
        public string estabnome { get; set; }
        public decimal codisiva { get; set; }
        public string motivoisiva { get; set; }
        public decimal acerto { get; set; }
        public decimal numcaixa { get; set; }
        public System.DateTime datcaixa { get; set; }
        public decimal codsec { get; set; }
        public string descsector { get; set; }
        public decimal posto { get; set; }
        public bool fechado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factl> Factl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cc> cc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formasp> formasp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactPag> FactPag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factprest> factprest { get; set; }
    }
}
