//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class formasp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formasp()
        {
            this.mvt = new HashSet<mvt>();
        }
    
        public string titulo { get; set; }
        public string numtitulo { get; set; }
        public System.DateTime dcheque { get; set; }
        public string banco { get; set; }
        public string contatesoura { get; set; }
        public decimal valor { get; set; }
        public decimal codtz { get; set; }
        public bool numer { get; set; }
        public bool tipo { get; set; }
        public bool ObgTitulo { get; set; }
        public string formaspstamp { get; set; }
        public string rclstamp { get; set; }
        public string rdstamp { get; set; }
        public string Factstamp { get; set; }
        public string Faccstamp { get; set; }
        public string pgfstamp { get; set; }
        public string rdfstamp { get; set; }
        public bool status { get; set; }
        public string distamp { get; set; }
        public decimal cpoc { get; set; }
        public decimal contaPgc { get; set; }
        public string origem { get; set; }
        public decimal mvalor { get; set; }
    
        public virtual Fact Fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvt> mvt { get; set; }
        public virtual RCL RCL { get; set; }
        public virtual pgf pgf { get; set; }
        public virtual rdf rdf { get; set; }
        public virtual rd rd { get; set; }
        public virtual Facc Facc { get; set; }
    }
}
