//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HBEntities : DbContext
    {
        public HBEntities()
            : base("name=HBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_param> a_param { get; set; }
        public virtual DbSet<apparam> apparam { get; set; }
        public virtual DbSet<diario> diario { get; set; }
        public virtual DbSet<dc> dc { get; set; }
        public virtual DbSet<dcli> dcli { get; set; }
        public virtual DbSet<Lcont> Lcont { get; set; }
    }
}
