//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lcont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lcont()
        {
            this.ml = new HashSet<ml>();
        }
    
        public string Lcontstamp { get; set; }
        public string dinome { get; set; }
        public decimal dilno { get; set; }
        public string docnome { get; set; }
        public string adoc { get; set; }
        public System.DateTime data { get; set; }
        public decimal mes { get; set; }
        public decimal dia { get; set; }
        public decimal dino { get; set; }
        public decimal doctipo { get; set; }
        public decimal debana { get; set; }
        public decimal debord { get; set; }
        public decimal debfin { get; set; }
        public decimal creana { get; set; }
        public decimal creord { get; set; }
        public decimal crefin { get; set; }
        public decimal edebana { get; set; }
        public decimal edebord { get; set; }
        public decimal edebfin { get; set; }
        public decimal ecreana { get; set; }
        public decimal ecreord { get; set; }
        public decimal ecrefin { get; set; }
        public string memissao { get; set; }
        public string ncont { get; set; }
        public decimal ano { get; set; }
        public decimal cambio { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ml> ml { get; set; }
    }
}
