//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        public decimal Mesano { get; set; }
        public string descricao { get; set; }
        public string imagem { get; set; }
        public bool Inactivo { get; set; }
        public decimal TopImg { get; set; }
        public decimal LeftImg { get; set; }
        public decimal Codloc { get; set; }
        public string DescLocal { get; set; }
        public string Mesasstamp { get; set; }
        public string LocMesasstamp { get; set; }
        public decimal Codigo { get; set; }
        public bool status { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    
        public virtual LocMesas LocMesas { get; set; }
    }
}
