//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml
    {
        public string mlstamp { get; set; }
        public string dinome { get; set; }
        public decimal dilno { get; set; }
        public string docnome { get; set; }
        public string adoc { get; set; }
        public System.DateTime data { get; set; }
        public decimal mes { get; set; }
        public decimal dia { get; set; }
        public string conta { get; set; }
        public string descricao { get; set; }
        public string rubrica { get; set; }
        public decimal deb { get; set; }
        public decimal cre { get; set; }
        public decimal edeb { get; set; }
        public decimal ecre { get; set; }
        public decimal dino { get; set; }
        public string descritivo { get; set; }
        public string cct { get; set; }
        public bool debl { get; set; }
        public bool vemdedc { get; set; }
        public string recapit { get; set; }
        public string ncont { get; set; }
        public decimal recapval { get; set; }
        public decimal docno { get; set; }
        public decimal doctipo { get; set; }
        public decimal ordem { get; set; }
        public bool separa { get; set; }
        public string Lcontstamp { get; set; }
        public bool vemdoext { get; set; }
        public decimal erecapval { get; set; }
        public decimal lordem { get; set; }
        public string npt { get; set; }
        public string bastamp { get; set; }
        public string intid { get; set; }
        public decimal idorigem { get; set; }
        public string origem { get; set; }
        public bool reco { get; set; }
        public string extracto { get; set; }
        public string oristamp { get; set; }
        public string olcodigo { get; set; }
        public string sgrupo { get; set; }
        public string grupo { get; set; }
        public decimal debm { get; set; }
        public decimal crem { get; set; }
        public string pncont { get; set; }
        public bool conf1 { get; set; }
        public bool conf2 { get; set; }
        public string codis { get; set; }
        public string czonag { get; set; }
        public string codisconf { get; set; }
        public string obs { get; set; }
        public string chave { get; set; }
        public string numcontrepres { get; set; }
        public string codprovincia { get; set; }
        public decimal cambio { get; set; }
        public string paistamp { get; set; }
    
        public virtual Lcont Lcont { get; set; }
    }
}
