//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fact> Fact { get; set; }
        public virtual DbSet<Factl> Factl { get; set; }
        public virtual DbSet<cc> cc { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<fcc> fcc { get; set; }
        public virtual DbSet<formasp> formasp { get; set; }
        public virtual DbSet<a_fpagam> a_fpagam { get; set; }
        public virtual DbSet<mvt> mvt { get; set; }
        public virtual DbSet<Trf> Trf { get; set; }
        public virtual DbSet<Vend> Vend { get; set; }
        public virtual DbSet<starm> starm { get; set; }
        public virtual DbSet<stcp> stcp { get; set; }
        public virtual DbSet<RCL> RCL { get; set; }
        public virtual DbSet<RCLL> RCLL { get; set; }
        public virtual DbSet<tdi> tdi { get; set; }
        public virtual DbSet<tdoc> tdoc { get; set; }
        public virtual DbSet<a_usr> a_usr { get; set; }
        public virtual DbSet<di> di { get; set; }
        public virtual DbSet<mstk> mstk { get; set; }
        public virtual DbSet<pgf> pgf { get; set; }
        public virtual DbSet<rd> rd { get; set; }
        public virtual DbSet<rdf> rdf { get; set; }
        public virtual DbSet<rdfl> rdfl { get; set; }
        public virtual DbSet<rdl> rdl { get; set; }
        public virtual DbSet<dil> dil { get; set; }
        public virtual DbSet<dil3> dil3 { get; set; }
        public virtual DbSet<Facc> Facc { get; set; }
        public virtual DbSet<Faccl> Faccl { get; set; }
        public virtual DbSet<faccprest> faccprest { get; set; }
        public virtual DbSet<Rlt> Rlt { get; set; }
        public virtual DbSet<tdocf> tdocf { get; set; }
        public virtual DbSet<docmodulo> docmodulo { get; set; }
        public virtual DbSet<TRcl> TRcl { get; set; }
        public virtual DbSet<Trd> Trd { get; set; }
        public virtual DbSet<Trdf> Trdf { get; set; }
        public virtual DbSet<Tpgf> Tpgf { get; set; }
        public virtual DbSet<pgfl> pgfl { get; set; }
        public virtual DbSet<Armazens> Armazens { get; set; }
        public virtual DbSet<st> st { get; set; }
        public virtual DbSet<Lcont> Lcont { get; set; }
        public virtual DbSet<ml> ml { get; set; }
        public virtual DbSet<pgc> pgc { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
        public virtual DbSet<FactPag> FactPag { get; set; }
        public virtual DbSet<factprest> factprest { get; set; }
        public virtual DbSet<Ent> Ent { get; set; }
        public virtual DbSet<a_param> a_param { get; set; }
        public virtual DbSet<apparam> apparam { get; set; }
        public virtual DbSet<a_usrmodulo> a_usrmodulo { get; set; }
        public virtual DbSet<acessos> acessos { get; set; }
        public virtual DbSet<rltusers> rltusers { get; set; }
        public virtual DbSet<LocMesas> LocMesas { get; set; }
        public virtual DbSet<Mesas> Mesas { get; set; }
        public virtual DbSet<Caixa> Caixa { get; set; }
        public virtual DbSet<pe> pe { get; set; }
        public virtual DbSet<pecontra> pecontra { get; set; }
        public virtual DbSet<pedesc> pedesc { get; set; }
        public virtual DbSet<pefalta> pefalta { get; set; }
        public virtual DbSet<peferias> peferias { get; set; }
        public virtual DbSet<pehextra> pehextra { get; set; }
        public virtual DbSet<pesub> pesub { get; set; }
        public virtual DbSet<pj> pj { get; set; }
        public virtual DbSet<Process> Process { get; set; }
    }
}
