//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstk
    {
        public string mstkstamp { get; set; }
        public string oristamp { get; set; }
        public string Stampcab { get; set; }
        public string Origem { get; set; }
        public System.DateTime data { get; set; }
        public string tipodoc { get; set; }
        public decimal nrdoc { get; set; }
        public string documento { get; set; }
        public decimal numdoc { get; set; }
        public string @ref { get; set; }
        public string descricao { get; set; }
        public decimal entrada { get; set; }
        public decimal saida { get; set; }
        public decimal codarm { get; set; }
        public decimal preco { get; set; }
        public string moeda { get; set; }
        public decimal entidade { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public System.DateTime datahora { get; set; }
        public string lote { get; set; }
        public decimal codmovstk { get; set; }
        public string descmovstk { get; set; }
        public string numinterno { get; set; }
        public string Factstamp { get; set; }
        public string Faccstamp { get; set; }
        public string Distamp { get; set; }
        public string Ivstamp { get; set; }
        public string Factlstamp { get; set; }
        public string Facclstamp { get; set; }
        public string Dilstamp { get; set; }
        public string Ivlstamp { get; set; }
        public string Turno { get; set; }
        public string Vendedor { get; set; }
        public decimal codvend { get; set; }
        public string serie { get; set; }
        public bool ivainc { get; set; }
        public decimal tabiva { get; set; }
        public decimal txiva { get; set; }
        public decimal preco2 { get; set; }
        public decimal preco3 { get; set; }
        public System.DateTime lotevalid { get; set; }
        public System.DateTime lotelimft { get; set; }
        public bool usalote { get; set; }
        public decimal qttmedida { get; set; }
        public decimal totalmedida { get; set; }
    
        public virtual Factl Factl { get; set; }
        public virtual dil dil { get; set; }
        public virtual Faccl Faccl { get; set; }
    }
}
