//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pe()
        {
            this.pecontra = new HashSet<pecontra>();
            this.pedesc = new HashSet<pedesc>();
            this.peferias = new HashSet<peferias>();
            this.pesub = new HashSet<pesub>();
        }
    
        public string pestamp { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string morada { get; set; }
        public string Locali { get; set; }
        public string Natural { get; set; }
        public string Nacional { get; set; }
        public string Contacto { get; set; }
        public string email { get; set; }
        public System.DateTime datanasc { get; set; }
        public string ecivil { get; set; }
        public string pai { get; set; }
        public string mae { get; set; }
        public string sexo { get; set; }
        public decimal codstatus { get; set; }
        public string descstatus { get; set; }
        public decimal codsit { get; set; }
        public string Situacao { get; set; }
        public decimal nuit { get; set; }
        public decimal codcat { get; set; }
        public string desccat { get; set; }
        public decimal codprof { get; set; }
        public string descprof { get; set; }
        public System.DateTime dataadm { get; set; }
        public string tipodocum { get; set; }
        public string numdocum { get; set; }
        public string locemiss { get; set; }
        public System.DateTime dataemiss { get; set; }
        public System.DateTime documvalid { get; set; }
        public decimal codhabliter { get; set; }
        public string habliter { get; set; }
        public string codbanco { get; set; }
        public string banco { get; set; }
        public decimal numconta { get; set; }
        public decimal Nib { get; set; }
        public bool trf { get; set; }
        public bool ntabelado { get; set; }
        public bool Ponto { get; set; }
        public string Pontonome { get; set; }
        public decimal valbase { get; set; }
        public decimal codirps { get; set; }
        public string descirps { get; set; }
        public decimal nrdep { get; set; }
        public decimal codsgs { get; set; }
        public string descsgs { get; set; }
        public decimal numsgs { get; set; }
        public decimal codtiposgs { get; set; }
        public string desctiposgs { get; set; }
        public string numsindic { get; set; }
        public decimal codsindic { get; set; }
        public string descsindic { get; set; }
        public decimal persindic { get; set; }
        public decimal codlevel1 { get; set; }
        public string desclevel1 { get; set; }
        public decimal codlevel2 { get; set; }
        public string desclevel2 { get; set; }
        public decimal codlevel3 { get; set; }
        public string desclevel3 { get; set; }
        public decimal codlevel4 { get; set; }
        public string desclevel4 { get; set; }
        public string codccusto { get; set; }
        public string desccusto { get; set; }
        public string foto { get; set; }
        public string obs { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pecontra> pecontra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedesc> pedesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peferias> peferias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pesub> pesub { get; set; }
    }
}
