//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pehextra
    {
        public decimal no { get; set; }
        public string nome { get; set; }
        public decimal Horas { get; set; }
        public bool processado { get; set; }
        public decimal ano { get; set; }
        public decimal nrmes { get; set; }
        public string mes { get; set; }
        public string pehextrastamp { get; set; }
        public string pestamp { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    }
}
