//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesub
    {
        public string pesubstamp { get; set; }
        public string pestamp { get; set; }
        public decimal codigo { get; set; }
        public string descricao { get; set; }
        public decimal Valor { get; set; }
        public decimal tipo { get; set; }
        public decimal no { get; set; }
        public bool status { get; set; }
    }
}
