//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pgc
    {
        public string pgcstamp { get; set; }
        public string conta { get; set; }
        public string descricao { get; set; }
        public string ncont { get; set; }
        public bool integracao { get; set; }
        public string contaiva { get; set; }
        public decimal codiva { get; set; }
        public decimal codiva2 { get; set; }
        public decimal taxaiva { get; set; }
        public string dbcr { get; set; }
        public string dbdb { get; set; }
        public string crdb { get; set; }
        public string crcr { get; set; }
        public System.DateTime udata { get; set; }
        public bool multicc { get; set; }
        public string qualci { get; set; }
        public string obs { get; set; }
        public string recapit { get; set; }
        public string local { get; set; }
        public decimal contado { get; set; }
        public string ollocal { get; set; }
        public bool lancaol { get; set; }
        public bool servcee { get; set; }
        public bool obrigacc { get; set; }
        public bool obrigaol { get; set; }
        public string ppconta { get; set; }
        public string ppdesc { get; set; }
        public bool obriganc { get; set; }
        public decimal ano { get; set; }
        public string olmoeda { get; set; }
        public bool doabrebe { get; set; }
        public string codis { get; set; }
        public bool pme { get; set; }
        public bool criadanoano { get; set; }
        public bool marcada { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    }
}
