//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pj
    {
        public string pjstamp { get; set; }
        public decimal Codigo { get; set; }
        public System.DateTime datini { get; set; }
        public System.DateTime datfim { get; set; }
        public decimal dias { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Descricao { get; set; }
        public bool Estado { get; set; }
        public System.DateTime datfecho { get; set; }
        public decimal tcusto { get; set; }
        public decimal Orc { get; set; }
        public decimal adenda { get; set; }
        public decimal adendaper { get; set; }
        public decimal totorc { get; set; }
        public decimal totft { get; set; }
        public decimal totftper { get; set; }
        public decimal totrec { get; set; }
        public decimal totrecper { get; set; }
        public decimal totprec { get; set; }
        public decimal totprecper { get; set; }
        public decimal totpft { get; set; }
        public decimal totpftper { get; set; }
        public decimal lucro { get; set; }
        public decimal lucroper { get; set; }
        public string obs { get; set; }
        public string pcontact { get; set; }
        public string tcontact { get; set; }
        public string tmpField { get; set; }
        public string ccusto { get; set; }
        public string codccu { get; set; }
        public string ccudesc { get; set; }
        public bool status { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    }
}
