//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjpe
    {
        public decimal No { get; set; }
        public string Nome { get; set; }
        public string funcao { get; set; }
        public string pjpestamp { get; set; }
        public string pjstamp { get; set; }
        public bool status { get; set; }
    }
}
