//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjst
    {
        public string @ref { get; set; }
        public string descricao { get; set; }
        public decimal Qtt { get; set; }
        public decimal Qttok { get; set; }
        public decimal QttFalta { get; set; }
        public decimal Preco { get; set; }
        public decimal Total { get; set; }
        public string pjststamp { get; set; }
        public string pjstamp { get; set; }
        public bool status { get; set; }
    }
}
