//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjvt
    {
        public string matricula { get; set; }
        public decimal Capacit { get; set; }
        public decimal nviagens { get; set; }
        public decimal Totqtt { get; set; }
        public string nome { get; set; }
        public decimal no { get; set; }
        public string pjvtstamp { get; set; }
        public string pjstamp { get; set; }
        public bool status { get; set; }
        public string marca { get; set; }
        public string tipo { get; set; }
        public decimal valorbase { get; set; }
    }
}
