//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prc
    {
        public string Prcstamp { get; set; }
        public string Processstamp { get; set; }
        public decimal nrmes { get; set; }
        public string mes { get; set; }
        public decimal ano { get; set; }
        public System.DateTime data { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public decimal codcat { get; set; }
        public string cat { get; set; }
        public decimal coddesc { get; set; }
        public decimal codfun { get; set; }
        public decimal codesc { get; set; }
        public decimal escalao { get; set; }
        public string indice { get; set; }
        public decimal codsec { get; set; }
        public decimal codcl { get; set; }
        public string classe { get; set; }
        public bool quota { get; set; }
        public string sind { get; set; }
        public decimal nsind { get; set; }
        public decimal codsit { get; set; }
        public string situacao { get; set; }
        public decimal BaseCateg { get; set; }
        public decimal totsub { get; set; }
        public decimal totabonus { get; set; }
        public decimal totdesc { get; set; }
        public decimal liquido { get; set; }
        public string obs { get; set; }
        public bool fechado { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public decimal valoremp { get; set; }
        public decimal val_emp { get; set; }
        public decimal SegSocEmp { get; set; }
    }
}
