//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prcdesc
    {
        public decimal codigo { get; set; }
        public string descricao { get; set; }
        public decimal taxa { get; set; }
        public decimal Valor { get; set; }
        public string Prcdescstamp { get; set; }
        public string Prcstamp { get; set; }
        public decimal tipodesc { get; set; }
        public decimal tipo { get; set; }
        public bool Fixo { get; set; }
        public bool status { get; set; }
        public decimal taxa2 { get; set; }
        public decimal valor2 { get; set; }
    }
}
