//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodarm
    {
        public string prodarmstamp { get; set; }
        public string @ref { get; set; }
        public decimal codarm { get; set; }
        public string descarm { get; set; }
        public decimal stock { get; set; }
        public bool status { get; set; }
    }
}
