//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCL()
        {
            this.cc = new HashSet<cc>();
            this.formasp = new HashSet<formasp>();
            this.RCLL = new HashSet<RCLL>();
        }
    
        public string Rclstamp { get; set; }
        public decimal numero { get; set; }
        public System.DateTime data { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string moeda { get; set; }
        public string Banco { get; set; }
        public decimal total { get; set; }
        public decimal mtotal { get; set; }
        public string obs { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool process { get; set; }
        public System.DateTime dprocess { get; set; }
        public bool anulado { get; set; }
        public string ccusto { get; set; }
        public decimal numdoc { get; set; }
        public string sigla { get; set; }
        public string nomedoc { get; set; }
        public decimal codmovcc { get; set; }
        public string descmovcc { get; set; }
        public string nomecomerc { get; set; }
        public bool integra { get; set; }
        public decimal nodiario { get; set; }
        public string diario { get; set; }
        public decimal ndocCont { get; set; }
        public string descDocCont { get; set; }
        public decimal estabno { get; set; }
        public string estabnome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cc> cc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formasp> formasp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCLL> RCLL { get; set; }
    }
}
