//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdl
    {
        public decimal ordem { get; set; }
        public string descricao { get; set; }
        public decimal valorl { get; set; }
        public decimal mvalorl { get; set; }
        public string rdstamp { get; set; }
        public string rdlstamp { get; set; }
        public bool status { get; set; }
    
        public virtual rd rd { get; set; }
    }
}
