//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rlt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rlt()
        {
            this.docmodulo = new HashSet<docmodulo>();
            this.rltusers = new HashSet<rltusers>();
        }
    
        public string rltstamp { get; set; }
        public decimal numero { get; set; }
        public string descricao { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public decimal Tipofilter { get; set; }
        public bool campotabela1 { get; set; }
        public bool Lista { get; set; }
        public bool usaca { get; set; }
        public string ComboQry1 { get; set; }
        public decimal tmColunas { get; set; }
        public string tmGrid { get; set; }
        public string clnBold { get; set; }
        public string clmMask { get; set; }
        public string clnHeader { get; set; }
        public string clnAlign { get; set; }
        public string clnCor { get; set; }
        public string clnTab { get; set; }
        public bool clnReport { get; set; }
        public string crQuery { get; set; }
        public bool menuint { get; set; }
        public string filefrx { get; set; }
        public string filefrt { get; set; }
        public bool painel { get; set; }
        public bool btncriadoc { get; set; }
        public bool btndestino { get; set; }
        public bool btnorigem { get; set; }
        public string ecran { get; set; }
        public string tabela { get; set; }
        public bool campotabela2 { get; set; }
        public string ComboQry2 { get; set; }
        public string Titlocal2 { get; set; }
        public bool campotabela3 { get; set; }
        public string ComboQry3 { get; set; }
        public string Titlocal3 { get; set; }
        public bool campotabela4 { get; set; }
        public string ComboQry4 { get; set; }
        public string Titlocal4 { get; set; }
        public bool campotabela5 { get; set; }
        public string ComboQry5 { get; set; }
        public string Titlocal5 { get; set; }
        public bool campotabela6 { get; set; }
        public string ComboQry6 { get; set; }
        public string Titlocal6 { get; set; }
        public bool campotabela7 { get; set; }
        public string ComboQry7 { get; set; }
        public string Titlocal7 { get; set; }
        public bool campotabela8 { get; set; }
        public string ComboQry8 { get; set; }
        public string Titlocal8 { get; set; }
        public bool campotabela9 { get; set; }
        public string ComboQry9 { get; set; }
        public string Titlocal9 { get; set; }
        public decimal TipoRlt { get; set; }
        public bool rltGrafico { get; set; }
        public string titlocal1 { get; set; }
        public decimal codcampo1 { get; set; }
        public string mascampo1 { get; set; }
        public decimal codcampo2 { get; set; }
        public string mascampo2 { get; set; }
        public decimal codcampo3 { get; set; }
        public string mascampo3 { get; set; }
        public decimal codcampo4 { get; set; }
        public string mascampo4 { get; set; }
        public decimal codcampo5 { get; set; }
        public string mascampo5 { get; set; }
        public decimal codcampo6 { get; set; }
        public string mascampo6 { get; set; }
        public decimal codcampo7 { get; set; }
        public string mascampo7 { get; set; }
        public decimal codcampo8 { get; set; }
        public string mascampo8 { get; set; }
        public decimal codcampo9 { get; set; }
        public string mascampo9 { get; set; }
        public string filtros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docmodulo> docmodulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rltusers> rltusers { get; set; }
    }
}
