//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class rltusers
    {
        public decimal Codigo { get; set; }
        public string Descricao { get; set; }
        public string rltusersstamp { get; set; }
        public string rltstamp { get; set; }
        public bool Status { get; set; }
    
        public virtual Rlt Rlt { get; set; }
    }
}
