//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class st
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public st()
        {
            this.stcp = new HashSet<stcp>();
        }
    
        public string ststamp { get; set; }
        public string @ref { get; set; }
        public string descricao { get; set; }
        public bool servico { get; set; }
        public decimal tabiva { get; set; }
        public decimal txiva { get; set; }
        public decimal valor1 { get; set; }
        public decimal valor2 { get; set; }
        public decimal valor3 { get; set; }
        public decimal valor4 { get; set; }
        public decimal valor5 { get; set; }
        public bool valor1inc { get; set; }
        public bool valor2inc { get; set; }
        public bool valor3inc { get; set; }
        public bool valor4inc { get; set; }
        public bool valor5inc { get; set; }
        public string codfam { get; set; }
        public string famidesc { get; set; }
        public string codsubfam { get; set; }
        public string descsubfam { get; set; }
        public string codgrupo { get; set; }
        public string descgrupo { get; set; }
        public decimal codforn { get; set; }
        public string fornec { get; set; }
        public decimal upc { get; set; }
        public string moedaupc { get; set; }
        public decimal Stocktotal { get; set; }
        public string codbarras { get; set; }
        public string medida { get; set; }
        public bool nnegativo { get; set; }
        public bool avisaneg { get; set; }
        public decimal Pontoecom { get; set; }
        public bool usalote { get; set; }
        public string obs { get; set; }
        public bool inactivo { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool nmovstk { get; set; }
        public decimal reserva { get; set; }
        public decimal previsto { get; set; }
        public decimal valor11 { get; set; }
        public decimal valor21 { get; set; }
        public decimal valor31 { get; set; }
        public decimal valor41 { get; set; }
        public decimal valor51 { get; set; }
        public bool composto { get; set; }
        public decimal codarmdf { get; set; }
        public string descarmdf { get; set; }
        public string codcontra { get; set; }
        public string contradesign { get; set; }
        public string codconjug { get; set; }
        public string conjugdesign { get; set; }
        public string imagem { get; set; }
        public bool pos { get; set; }
        public string descpos { get; set; }
        public decimal pond { get; set; }
        public string Campo1 { get; set; }
        public Nullable<decimal> contatz { get; set; }
        public string marca { get; set; }
        public string descmarca { get; set; }
        public decimal precoorig { get; set; }
        public decimal upciva { get; set; }
        public decimal pondiva { get; set; }
        public decimal pack { get; set; }
        public decimal cpoc { get; set; }
        public decimal cpoo { get; set; }
        public string submarca { get; set; }
        public string descsubmarca { get; set; }
        public string reffornec { get; set; }
        public string Desctecnica { get; set; }
        public bool usatec { get; set; }
        public string stfoto { get; set; }
        public bool refaddic { get; set; }
        public bool refintegra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stcp> stcp { get; set; }
    }
}
