//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tdi()
        {
            this.docmodulo = new HashSet<docmodulo>();
        }
    
        public string tdistamp { get; set; }
        public string descricao { get; set; }
        public string sigla { get; set; }
        public decimal tipo { get; set; }
        public string desctipo { get; set; }
        public string tiposigla { get; set; }
        public bool Alteranum { get; set; }
        public bool ctrlData { get; set; }
        public bool Armazem { get; set; }
        public decimal armdefeito { get; set; }
        public bool movstk { get; set; }
        public decimal codmovstk { get; set; }
        public string descmovstk { get; set; }
        public bool Composto { get; set; }
        public bool obgccusto { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool activo { get; set; }
        public bool defa { get; set; }
        public bool trf { get; set; }
        public decimal codmovstk2 { get; set; }
        public string descmovstk2 { get; set; }
        public decimal numdoc { get; set; }
        public bool reserva { get; set; }
        public bool noneg { get; set; }
        public bool Armapenas { get; set; }
        public bool prod { get; set; }
        public bool Copyqtt { get; set; }
        public bool copyvalor { get; set; }
        public bool prccusto { get; set; }
        public decimal armdefeito2 { get; set; }
        public bool Facturar { get; set; }
        public decimal ndocfact { get; set; }
        public string docfact { get; set; }
        public bool CopiaDocs { get; set; }
        public string Nomfile { get; set; }
        public string ecran { get; set; }
        public string Titimpress { get; set; }
        public bool copia { get; set; }
        public bool usaaprova { get; set; }
        public string descpreco { get; set; }
        public string campopreco { get; set; }
        public bool usafecho { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public bool usaemail { get; set; }
        public string destinationEmail { get; set; }
        public string subj { get; set; }
        public string emailText { get; set; }
        public bool usaattach { get; set; }
        public bool usaorigem { get; set; }
        public bool usadestino { get; set; }
        public bool usaanexo { get; set; }
        public bool ligapj { get; set; }
        public bool obrigapj { get; set; }
        public bool usaserie { get; set; }
        public bool autoemail { get; set; }
        public string condcopia { get; set; }
        public bool orc { get; set; }
        public Nullable<bool> movtz { get; set; }
        public Nullable<decimal> tipomovtz { get; set; }
        public bool noentid { get; set; }
        public bool regrd { get; set; }
        public bool usalote { get; set; }
        public bool dotacao { get; set; }
        public bool aprova { get; set; }
        public string maskqtt { get; set; }
        public string maskpreco { get; set; }
        public string maskoprecos { get; set; }
        public string expressemidoc { get; set; }
        public string expresstitulo { get; set; }
        public bool introdir { get; set; }
        public decimal tipodoc { get; set; }
        public string pastascan { get; set; }
        public string tipoimg { get; set; }
        public bool saveimg { get; set; }
        public string nomefiles { get; set; }
        public bool usatec { get; set; }
        public bool nopergtec { get; set; }
        public bool obrigalote { get; set; }
        public bool usaqttmedida { get; set; }
        public string descqttmedida { get; set; }
        public bool noalteramedida { get; set; }
        public decimal dias { get; set; }
        public string ccusto { get; set; }
        public string contastesoura { get; set; }
        public decimal codtz { get; set; }
        public string titulo { get; set; }
        public bool nalteratz { get; set; }
        public bool diagua { get; set; }
        public bool etpemiss { get; set; }
        public bool etpimpress { get; set; }
        public bool etpemail { get; set; }
        public string etpemisstxt { get; set; }
        public string etpimpresstxt { get; set; }
        public string etpemailtxt { get; set; }
        public bool ctrqttorig { get; set; }
        public bool precocl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docmodulo> docmodulo { get; set; }
    }
}
