//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trdf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trdf()
        {
            this.docmodulo = new HashSet<docmodulo>();
        }
    
        public string Trdfstamp { get; set; }
        public decimal numdoc { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
        public string descmovcc { get; set; }
        public decimal codmovcc { get; set; }
        public string contastesoura { get; set; }
        public decimal codtz { get; set; }
        public string titulo { get; set; }
        public string ccusto { get; set; }
        public string obs { get; set; }
        public decimal entida { get; set; }
        public bool activo { get; set; }
        public bool Defa { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public bool usaanexo { get; set; }
        public bool usaemail { get; set; }
        public decimal tesouraPgc { get; set; }
        public bool etpemiss { get; set; }
        public bool etpimpress { get; set; }
        public bool etpemail { get; set; }
        public string etpemisstxt { get; set; }
        public string etpimpresstxt { get; set; }
        public string etpemailtxt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<docmodulo> docmodulo { get; set; }
    }
}
