//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trf()
        {
            this.mvt = new HashSet<mvt>();
        }
    
        public string Trfstamp { get; set; }
        public decimal Codigo { get; set; }
        public string numinterno { get; set; }
        public System.DateTime Data { get; set; }
        public string origem { get; set; }
        public decimal orinum { get; set; }
        public string moeda1 { get; set; }
        public string destino { get; set; }
        public decimal destnum { get; set; }
        public string moeda2 { get; set; }
        public decimal Valor { get; set; }
        public string obs { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string titulo { get; set; }
        public string numtitulo { get; set; }
        public string ccusto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvt> mvt { get; set; }
    }
}
