//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vend
    {
        public string vendstamp { get; set; }
        public decimal no { get; set; }
        public string nome { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string mail { get; set; }
        public string Morada { get; set; }
        public string tipo { get; set; }
        public string obs { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
    }
}
