//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vt()
        {
            this.vtcfg = new HashSet<vtcfg>();
            this.vtcorreias = new HashSet<vtcorreias>();
            this.vtfiltros = new HashSet<vtfiltros>();
            this.vtman = new HashSet<vtman>();
            this.vtmedpneus = new HashSet<vtmedpneus>();
            this.vtoleos = new HashSet<vtoleos>();
            this.vtoutros = new HashSet<vtoutros>();
        }
    
        public string vtstamp { get; set; }
        public decimal Codigo { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Motor { get; set; }
        public string Chassis { get; set; }
        public decimal anofab { get; set; }
        public decimal tara { get; set; }
        public decimal pesobruto { get; set; }
        public string Combustivel { get; set; }
        public string Pneus { get; set; }
        public decimal codentida { get; set; }
        public string Nomentida { get; set; }
        public System.DateTime valInspec { get; set; }
        public System.DateTime daquisic { get; set; }
        public string obs { get; set; }
        public decimal Status { get; set; }
        public string Descstatus { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string Seguradora { get; set; }
        public string Apolice { get; set; }
        public System.DateTime valapolice { get; set; }
        public decimal codtrl { get; set; }
        public string trailer { get; set; }
        public string Numlic { get; set; }
        public System.DateTime DatLic { get; set; }
        public System.DateTime validLic { get; set; }
        public string NumInspec { get; set; }
        public System.DateTime DatInspec { get; set; }
        public System.DateTime DatSegura { get; set; }
        public decimal Anomanifest { get; set; }
        public System.DateTime Datmanifest { get; set; }
        public System.DateTime Validmanifest { get; set; }
        public decimal capacit { get; set; }
        public bool Externa { get; set; }
        public decimal numdoc { get; set; }
        public string medveloc { get; set; }
        public decimal qttporkm { get; set; }
        public decimal capaclitros { get; set; }
        public string @ref { get; set; }
        public string stdesc { get; set; }
        public decimal codmarca { get; set; }
        public decimal tipo { get; set; }
        public string designacao { get; set; }
        public decimal valorbase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtcfg> vtcfg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtcorreias> vtcorreias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtfiltros> vtfiltros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtman> vtman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtmedpneus> vtmedpneus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtoleos> vtoleos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vtoutros> vtoutros { get; set; }
    }
}
