//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtcfg
    {
        public decimal codigo { get; set; }
        public string descricao { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime data { get; set; }
        public bool feito { get; set; }
        public string vtcfgstamp { get; set; }
        public string vtstamp { get; set; }
        public string distamp { get; set; }
        public string matricula { get; set; }
        public decimal valor2 { get; set; }
    
        public virtual vt vt { get; set; }
    }
}
