//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtman
    {
        public string matricula { get; set; }
        public decimal valparam { get; set; }
        public decimal Valkm { get; set; }
        public decimal diferenca { get; set; }
        public bool feito { get; set; }
        public string vtmanstamp { get; set; }
        public string vtstamp { get; set; }
        public string distamp { get; set; }
    
        public virtual vt vt { get; set; }
    }
}
