//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtmedpneus
    {
        public string descricao { get; set; }
        public decimal codigo { get; set; }
        public string vtmedpneusstamp { get; set; }
        public string vtstamp { get; set; }
    
        public virtual vt vt { get; set; }
    }
}
