//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtoleos
    {
        public string descricao { get; set; }
        public string reforig { get; set; }
        public string outraref1 { get; set; }
        public string outraref2 { get; set; }
        public string outraref3 { get; set; }
        public string outraref4 { get; set; }
        public decimal codigo { get; set; }
        public string qmc { get; set; }
        public System.DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public System.DateTime qmadathora { get; set; }
        public string vtoleosstamp { get; set; }
        public string vtstamp { get; set; }
    
        public virtual vt vt { get; set; }
    }
}
