namespace DMZ.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class uptdoct : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Tdoc", "Alteranum", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "CtrlData", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "CtrlPlaf", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Armdefeito", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Tdoc", "Recibo", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Movtes", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Composto", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Obgccusto", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Qmc", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Qmcdathora", c => c.DateTime(nullable: false));
            AddColumn("dbo.Tdoc", "Qma", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Qmadathora", c => c.DateTime(nullable: false));
            AddColumn("dbo.Tdoc", "Nalteratz", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Activo", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Defa", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Pos", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Introdir", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Copia", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Reserva", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Armapenas", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Copyqtt", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Copyvalor", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Prestacao", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Coment", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Titulo", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Facturar", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "ndocfact", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Tdoc", "docfact", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "CopiaDocs", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Nc", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Descdoc", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Noimp", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Nomfile", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Ecran", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Titimpress", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Obs2", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Descpreco", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Campopreco", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "No", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Tdoc", "Nome", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Usaemail", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Usaanexo", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Adjudica", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Aprova", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Expressemidoc", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Expresstitulo", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Autoemail", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Usaattach", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "DestinationEmail", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Subj", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "EmailText", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Maskqtt", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Maskpreco", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Maskoprecos", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Usatec", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Nopergtec", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Obrigalote", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Usaqttmedida", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Descqttmedida", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Noalteramedida", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Etpemiss", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Etpimpress", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Etpemail", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Etpemisstxt", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Etpimpresstxt", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Etpemailtxt", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Ctrqttorig", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Tdoc", "Descricao", c => c.String(maxLength: 80));
            AlterColumn("dbo.Tdoc", "Armazem", c => c.Boolean(nullable: false));
            DropColumn("dbo.Tdoc", "Padrao");
            DropColumn("dbo.Tdoc", "Obgcc");
            DropColumn("dbo.Tdoc", "Codarm");
            DropColumn("dbo.Tdoc", "Status");
            DropColumn("dbo.Tdoc", "Obs");
            DropColumn("dbo.Tdoc", "Codcc");
            DropColumn("dbo.Tdoc", "NCredito");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Tdoc", "NCredito", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Codcc", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Tdoc", "Obs", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Status", c => c.String(maxLength: 80));
            AddColumn("dbo.Tdoc", "Codarm", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Tdoc", "Obgcc", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tdoc", "Padrao", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Tdoc", "Armazem", c => c.String(maxLength: 80));
            AlterColumn("dbo.Tdoc", "Descricao", c => c.String(nullable: false, maxLength: 80));
            DropColumn("dbo.Tdoc", "Ctrqttorig");
            DropColumn("dbo.Tdoc", "Etpemailtxt");
            DropColumn("dbo.Tdoc", "Etpimpresstxt");
            DropColumn("dbo.Tdoc", "Etpemisstxt");
            DropColumn("dbo.Tdoc", "Etpemail");
            DropColumn("dbo.Tdoc", "Etpimpress");
            DropColumn("dbo.Tdoc", "Etpemiss");
            DropColumn("dbo.Tdoc", "Noalteramedida");
            DropColumn("dbo.Tdoc", "Descqttmedida");
            DropColumn("dbo.Tdoc", "Usaqttmedida");
            DropColumn("dbo.Tdoc", "Obrigalote");
            DropColumn("dbo.Tdoc", "Nopergtec");
            DropColumn("dbo.Tdoc", "Usatec");
            DropColumn("dbo.Tdoc", "Maskoprecos");
            DropColumn("dbo.Tdoc", "Maskpreco");
            DropColumn("dbo.Tdoc", "Maskqtt");
            DropColumn("dbo.Tdoc", "EmailText");
            DropColumn("dbo.Tdoc", "Subj");
            DropColumn("dbo.Tdoc", "DestinationEmail");
            DropColumn("dbo.Tdoc", "Usaattach");
            DropColumn("dbo.Tdoc", "Autoemail");
            DropColumn("dbo.Tdoc", "Expresstitulo");
            DropColumn("dbo.Tdoc", "Expressemidoc");
            DropColumn("dbo.Tdoc", "Aprova");
            DropColumn("dbo.Tdoc", "Adjudica");
            DropColumn("dbo.Tdoc", "Usaanexo");
            DropColumn("dbo.Tdoc", "Usaemail");
            DropColumn("dbo.Tdoc", "Nome");
            DropColumn("dbo.Tdoc", "No");
            DropColumn("dbo.Tdoc", "Campopreco");
            DropColumn("dbo.Tdoc", "Descpreco");
            DropColumn("dbo.Tdoc", "Obs2");
            DropColumn("dbo.Tdoc", "Titimpress");
            DropColumn("dbo.Tdoc", "Ecran");
            DropColumn("dbo.Tdoc", "Nomfile");
            DropColumn("dbo.Tdoc", "Noimp");
            DropColumn("dbo.Tdoc", "Descdoc");
            DropColumn("dbo.Tdoc", "Nc");
            DropColumn("dbo.Tdoc", "CopiaDocs");
            DropColumn("dbo.Tdoc", "docfact");
            DropColumn("dbo.Tdoc", "ndocfact");
            DropColumn("dbo.Tdoc", "Facturar");
            DropColumn("dbo.Tdoc", "Titulo");
            DropColumn("dbo.Tdoc", "Coment");
            DropColumn("dbo.Tdoc", "Prestacao");
            DropColumn("dbo.Tdoc", "Copyvalor");
            DropColumn("dbo.Tdoc", "Copyqtt");
            DropColumn("dbo.Tdoc", "Armapenas");
            DropColumn("dbo.Tdoc", "Reserva");
            DropColumn("dbo.Tdoc", "Copia");
            DropColumn("dbo.Tdoc", "Introdir");
            DropColumn("dbo.Tdoc", "Pos");
            DropColumn("dbo.Tdoc", "Defa");
            DropColumn("dbo.Tdoc", "Activo");
            DropColumn("dbo.Tdoc", "Nalteratz");
            DropColumn("dbo.Tdoc", "Qmadathora");
            DropColumn("dbo.Tdoc", "Qma");
            DropColumn("dbo.Tdoc", "Qmcdathora");
            DropColumn("dbo.Tdoc", "Qmc");
            DropColumn("dbo.Tdoc", "Obgccusto");
            DropColumn("dbo.Tdoc", "Composto");
            DropColumn("dbo.Tdoc", "Movtes");
            DropColumn("dbo.Tdoc", "Recibo");
            DropColumn("dbo.Tdoc", "Armdefeito");
            DropColumn("dbo.Tdoc", "CtrlPlaf");
            DropColumn("dbo.Tdoc", "CtrlData");
            DropColumn("dbo.Tdoc", "Alteranum");
        }
    }
}
