namespace DMZ.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addtablefact : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Cc",
                c => new
                    {
                        ccstamp = c.String(nullable: false, maxLength: 80),
                        origem = c.String(maxLength: 80),
                        oristamp = c.String(maxLength: 80),
                        nrdoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        no = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nome = c.String(maxLength: 80),
                        data = c.DateTime(nullable: false),
                        vencim = c.DateTime(nullable: false),
                        debito = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitom = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitof = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitofm = c.Decimal(nullable: false, precision: 9, scale: 0),
                        credito = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditom = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditof = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditofm = c.Decimal(nullable: false, precision: 9, scale: 0),
                        qmc = c.String(maxLength: 80),
                        qmcdathora = c.DateTime(nullable: false),
                        qma = c.String(maxLength: 80),
                        qmadathora = c.DateTime(nullable: false),
                        documento = c.String(maxLength: 80),
                        Moeda = c.String(maxLength: 80),
                        saldo = c.Decimal(nullable: false, precision: 9, scale: 0),
                        codmov = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Factstamp = c.String(maxLength: 80),
                        rclstamp = c.String(maxLength: 80),
                        rdstamp = c.String(maxLength: 80),
                        ccusto = c.String(maxLength: 80),
                        numinterno = c.String(maxLength: 80),
                        estabno = c.Decimal(nullable: false, precision: 9, scale: 0),
                        estabnome = c.String(maxLength: 80),
                    })
                .PrimaryKey(t => t.ccstamp)
                .ForeignKey("dbo.Fact", t => t.Factstamp)
                .Index(t => t.Factstamp);
            
            CreateTable(
                "dbo.Fact",
                c => new
                    {
                        Factstamp = c.String(nullable: false, maxLength: 80),
                        Numdoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Sigla = c.String(maxLength: 80),
                        Numero = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Data = c.DateTime(nullable: false),
                        Dataven = c.DateTime(nullable: false),
                        No = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Nome = c.String(maxLength: 80),
                        Morada = c.String(maxLength: 80),
                        Telefone = c.String(maxLength: 80),
                        Fax = c.String(maxLength: 80),
                        Nuit = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Email = c.String(maxLength: 80),
                        Moeda = c.String(maxLength: 80),
                        Subtotal = c.Decimal(nullable: false, precision: 9, scale: 0),
                        perdesc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        desconto = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Totaliva = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Total = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Msubtotal = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Mdesconto = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Mtotaliva = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Mtotal = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Codvend = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Vendedor = c.String(maxLength: 80),
                        Cambio = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Cambfixo = c.Boolean(nullable: false),
                        Impresso = c.Boolean(nullable: false),
                        Usrimpress = c.String(maxLength: 80),
                        Impressodh = c.DateTime(nullable: false),
                        Anulado = c.Boolean(nullable: false),
                        CodInterno = c.String(maxLength: 80),
                        Movtz = c.Boolean(nullable: false),
                        Movstk = c.Boolean(nullable: false),
                        Codmovstk = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Movcc = c.Boolean(nullable: false),
                        Codmovcc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Nomedoc = c.String(maxLength: 80),
                        Descmovcc = c.String(maxLength: 80),
                        Descmovstk = c.String(maxLength: 80),
                        Numinterno = c.String(maxLength: 80),
                        Ccusto = c.String(maxLength: 80),
                        obs = c.String(maxLength: 80),
                        oristamp = c.String(maxLength: 80),
                        aprovado = c.Boolean(nullable: false),
                        adjudicado = c.Boolean(nullable: false),
                        origem = c.String(maxLength: 80),
                        coment = c.String(maxLength: 80),
                        codarm = c.Decimal(nullable: false, precision: 9, scale: 0),
                        codturno = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Turno = c.String(maxLength: 80),
                        Mesa = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Fechada = c.Boolean(nullable: false),
                        Isiva = c.Boolean(nullable: false),
                        clivainc = c.Boolean(nullable: false),
                        Campo1 = c.String(maxLength: 80),
                        Campo2 = c.String(maxLength: 80),
                        tipodoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        no2 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nome2 = c.String(maxLength: 80),
                        Morada2 = c.String(maxLength: 80),
                        Localidade2 = c.String(maxLength: 80),
                        codagree = c.String(maxLength: 80),
                        nomecomerc = c.String(maxLength: 80),
                        dadjudicado = c.DateTime(nullable: false),
                        nadjudicado = c.String(maxLength: 80),
                        integra = c.Boolean(nullable: false),
                        noDiario = c.Decimal(nullable: false, precision: 9, scale: 0),
                        diario = c.String(maxLength: 80),
                        nDocCont = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descDocCont = c.String(maxLength: 80),
                        contabilizado = c.Boolean(nullable: false),
                        reserva = c.Boolean(nullable: false),
                        lant = c.Decimal(nullable: false, precision: 9, scale: 0),
                        lact = c.Decimal(nullable: false, precision: 9, scale: 0),
                        lreal = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ldata = c.DateTime(nullable: false),
                        tipoentida = c.String(maxLength: 80),
                        zona = c.String(maxLength: 80),
                        ncont = c.String(maxLength: 80),
                        codzona = c.Decimal(nullable: false, precision: 9, scale: 0),
                        fleitura = c.String(maxLength: 80),
                        ncontador = c.String(maxLength: 80),
                        tprocess = c.String(maxLength: 80),
                        nrfornec = c.String(maxLength: 80),
                        ndeclara = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Refcl = c.String(maxLength: 80),
                        tpdescmercad = c.String(maxLength: 80),
                        volumes = c.String(maxLength: 80),
                        cifmoeda = c.Decimal(nullable: false, precision: 9, scale: 0),
                        cifmt = c.Decimal(nullable: false, precision: 9, scale: 0),
                        cifusd = c.Decimal(nullable: false, precision: 9, scale: 0),
                        cambiousd = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Moeda2 = c.String(maxLength: 80),
                        pjno = c.Decimal(nullable: false, precision: 9, scale: 0),
                        pjstamp = c.String(maxLength: 80),
                        optintro = c.Decimal(nullable: false, precision: 9, scale: 0),
                        calcfrete = c.Boolean(nullable: false),
                        calcseguro = c.Boolean(nullable: false),
                        fob = c.Decimal(nullable: false, precision: 9, scale: 0),
                        frete = c.Decimal(nullable: false, precision: 9, scale: 0),
                        seguro = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ocusto = c.Decimal(nullable: false, precision: 9, scale: 0),
                        estabno = c.Decimal(nullable: false, precision: 9, scale: 0),
                        estabnome = c.String(maxLength: 80),
                        codisiva = c.Decimal(nullable: false, precision: 9, scale: 0),
                        motivoisiva = c.String(maxLength: 80),
                        acerto = c.Decimal(nullable: false, precision: 9, scale: 0),
                        numcaixa = c.Decimal(nullable: false, precision: 9, scale: 0),
                        datcaixa = c.DateTime(nullable: false),
                        codsec = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descsector = c.String(maxLength: 80),
                        posto = c.Decimal(nullable: false, precision: 9, scale: 0),
                        fechado = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.Factstamp);
            
            CreateTable(
                "dbo.Factl",
                c => new
                    {
                        Factlstamp = c.String(nullable: false, maxLength: 80),
                        Factstamp = c.String(maxLength: 80),
                        numdoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        sigla = c.String(maxLength: 80),
                        _ref = c.String(name: "ref", maxLength: 80),
                        descricao = c.String(maxLength: 80),
                        quant = c.Decimal(nullable: false, precision: 9, scale: 0),
                        unidade = c.String(maxLength: 80),
                        armazem = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Preco = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Mpreco = c.Decimal(nullable: false, precision: 9, scale: 0),
                        tabiva = c.Decimal(nullable: false, precision: 9, scale: 0),
                        txiva = c.Decimal(nullable: false, precision: 9, scale: 0),
                        valival = c.Decimal(nullable: false, precision: 9, scale: 0),
                        mvalival = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ivainc = c.Boolean(nullable: false),
                        perdesc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descontol = c.Decimal(nullable: false, precision: 9, scale: 0),
                        mdescontol = c.Decimal(nullable: false, precision: 9, scale: 0),
                        subtotall = c.Decimal(precision: 9, scale: 0),
                        msubtotall = c.Decimal(nullable: false, precision: 9, scale: 0),
                        totall = c.Decimal(nullable: false, precision: 9, scale: 0),
                        mtotall = c.Decimal(precision: 9, scale: 0),
                        status = c.Boolean(nullable: false),
                        lote = c.String(maxLength: 80),
                        usadesign = c.Boolean(nullable: false),
                        servico = c.Boolean(nullable: false),
                        oristampl = c.String(maxLength: 80),
                        Dispon = c.Decimal(nullable: false, precision: 9, scale: 0),
                        QttOrig = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nmovstk = c.Boolean(nullable: false),
                        remotestamp = c.String(maxLength: 80),
                        oristamp = c.String(maxLength: 80),
                        Tit = c.Boolean(nullable: false),
                        ordem = c.Decimal(nullable: false, precision: 9, scale: 0),
                        stkprod = c.Boolean(nullable: false),
                        LineAnulado = c.Boolean(nullable: false),
                        Titstamp = c.String(maxLength: 80),
                        quant2 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        quant3 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        preco2 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        preco3 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        contatz = c.Decimal(precision: 9, scale: 0),
                        pack = c.Decimal(nullable: false, precision: 9, scale: 0),
                        cpoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        cpoo = c.Decimal(nullable: false, precision: 9, scale: 0),
                        usalote = c.Boolean(nullable: false),
                        composto = c.Boolean(nullable: false),
                        lotevalid = c.DateTime(nullable: false),
                        lotelimft = c.DateTime(nullable: false),
                        qttmedida = c.Decimal(nullable: false, precision: 9, scale: 0),
                        totalmedida = c.Decimal(nullable: false, precision: 9, scale: 0),
                        grupo = c.Decimal(nullable: false, precision: 9, scale: 0),
                        usaperlinha = c.Boolean(nullable: false),
                        perlinha = c.Decimal(nullable: false, precision: 9, scale: 0),
                        tipocheck = c.Decimal(nullable: false, precision: 9, scale: 0),
                        qttdecim = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.Factlstamp)
                .ForeignKey("dbo.Fact", t => t.Factstamp)
                .Index(t => t.Factstamp);
            
            CreateTable(
                "dbo.Fcc",
                c => new
                    {
                        Fccstamp = c.String(nullable: false, maxLength: 80),
                        Origem = c.String(maxLength: 80),
                        Oristamp = c.String(maxLength: 80),
                        nrdoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        no = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nome = c.String(maxLength: 80),
                        data = c.DateTime(nullable: false),
                        vencim = c.DateTime(nullable: false),
                        debito = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitom = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitof = c.Decimal(nullable: false, precision: 9, scale: 0),
                        debitofm = c.Decimal(nullable: false, precision: 9, scale: 0),
                        credito = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditom = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditof = c.Decimal(nullable: false, precision: 9, scale: 0),
                        creditofm = c.Decimal(nullable: false, precision: 9, scale: 0),
                        qmc = c.String(maxLength: 80),
                        qmcdathora = c.DateTime(nullable: false),
                        qma = c.String(maxLength: 80),
                        qmadathora = c.DateTime(nullable: false),
                        documento = c.String(maxLength: 80),
                        Moeda = c.String(maxLength: 80),
                        saldo = c.Decimal(nullable: false, precision: 9, scale: 0),
                        codmov = c.Decimal(nullable: false, precision: 9, scale: 0),
                        reffornec = c.String(maxLength: 80),
                        Faccstamp = c.String(maxLength: 80),
                        pgfstamp = c.String(maxLength: 80),
                        rdfstamp = c.String(maxLength: 80),
                        ccusto = c.String(maxLength: 80),
                        pgflstamp = c.String(maxLength: 80),
                        numinterno = c.String(maxLength: 80),
                    })
                .PrimaryKey(t => t.Fccstamp);
            
            CreateTable(
                "dbo.Formasp",
                c => new
                    {
                        Formaspstamp = c.String(nullable: false, maxLength: 80),
                        Titulo = c.String(maxLength: 80),
                        Numtitulo = c.String(maxLength: 80),
                        Dcheque = c.DateTime(nullable: false),
                        Banco = c.String(maxLength: 80),
                        Contatesoura = c.String(maxLength: 80),
                        Valor = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Codtz = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Numer = c.Boolean(nullable: false),
                        Tipo = c.Boolean(nullable: false),
                        ObgTitulo = c.Boolean(nullable: false),
                        Rclstamp = c.String(maxLength: 80),
                        Rdstamp = c.String(maxLength: 80),
                        Factstamp = c.String(maxLength: 80),
                        Faccstamp = c.String(maxLength: 80),
                        Pgfstamp = c.String(maxLength: 80),
                        Rdfstamp = c.String(maxLength: 80),
                        Status = c.Boolean(nullable: false),
                        Distamp = c.String(maxLength: 80),
                        Cpoc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ContaPgc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        Origem = c.String(maxLength: 80),
                        Mvalor = c.Decimal(nullable: false, precision: 9, scale: 0),
                    })
                .PrimaryKey(t => t.Formaspstamp)
                .ForeignKey("dbo.Fact", t => t.Factstamp)
                .Index(t => t.Factstamp);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Formasp", "Factstamp", "dbo.Fact");
            DropForeignKey("dbo.Cc", "Factstamp", "dbo.Fact");
            DropForeignKey("dbo.Factl", "Factstamp", "dbo.Fact");
            DropIndex("dbo.Formasp", new[] { "Factstamp" });
            DropIndex("dbo.Factl", new[] { "Factstamp" });
            DropIndex("dbo.Cc", new[] { "Factstamp" });
            DropTable("dbo.Formasp");
            DropTable("dbo.Fcc");
            DropTable("dbo.Factl");
            DropTable("dbo.Fact");
            DropTable("dbo.Cc");
        }
    }
}
