namespace DMZ.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class upddi2 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Di", "Codtz2", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "Desccodtz2", c => c.String(nullable: false, maxLength: 80));
            DropColumn("dbo.Di", "codturno");
            DropColumn("dbo.Di", "Usaaprova");
            DropColumn("dbo.Di", "Opcao1Other");
            DropColumn("dbo.Di", "Orc");
            DropColumn("dbo.Di", "dusequenc");
            DropColumn("dbo.Di", "duitems");
            DropColumn("dbo.Di", "estancia");
            DropColumn("dbo.Di", "regime");
            DropColumn("dbo.Di", "manifesto");
            DropColumn("dbo.Di", "doctransp");
            DropColumn("dbo.Di", "nregtransp");
            DropColumn("dbo.Di", "nvolumes");
            DropColumn("dbo.Di", "pembarque");
            DropColumn("dbo.Di", "nrcontpag");
            DropColumn("dbo.Di", "portdest");
            DropColumn("dbo.Di", "ngarant");
            DropColumn("dbo.Di", "mgarant");
            DropColumn("dbo.Di", "sgarant");
            DropColumn("dbo.Di", "prdestino");
            DropColumn("dbo.Di", "refdeclara");
            DropColumn("dbo.Di", "metaval");
            DropColumn("dbo.Di", "formpagadc");
            DropColumn("dbo.Di", "paisdest");
            DropColumn("dbo.Di", "nacional");
            DropColumn("dbo.Di", "locdescarg");
            DropColumn("dbo.Di", "condentreg");
            DropColumn("dbo.Di", "metpagament");
            DropColumn("dbo.Di", "fundo");
            DropColumn("dbo.Di", "prevarmaz");
            DropColumn("dbo.Di", "regarmaz");
            DropColumn("dbo.Di", "outrinfo");
            DropColumn("dbo.Di", "ptransp1");
            DropColumn("dbo.Di", "ptransp2");
            DropColumn("dbo.Di", "ptransp3");
            DropColumn("dbo.Di", "numselo");
            DropColumn("dbo.Di", "pbruto");
            DropColumn("dbo.Di", "outras");
            DropColumn("dbo.Di", "ntims");
            DropColumn("dbo.Di", "refcambial");
            DropColumn("dbo.Di", "refprocur");
            DropColumn("dbo.Di", "reflicenc");
            DropColumn("dbo.Di", "nisencao");
            DropColumn("dbo.Di", "datisencao");
            DropColumn("dbo.Di", "isdireito");
            DropColumn("dbo.Di", "isimpcons");
            DropColumn("dbo.Di", "issobretx");
            DropColumn("dbo.Di", "isiva");
            DropColumn("dbo.Di", "blegal");
            DropColumn("dbo.Di", "Locmercador");
            DropColumn("dbo.Di", "Proprietario");
            DropColumn("dbo.Di", "desestancia");
            DropColumn("dbo.Di", "desregime");
            DropColumn("dbo.Di", "desfrnteira");
            DropColumn("dbo.Di", "despembarque");
            DropColumn("dbo.Di", "despdestino1");
            DropColumn("dbo.Di", "deslocdescarg");
            DropColumn("dbo.Di", "descodentreg");
            DropColumn("dbo.Di", "desmetpagam");
            DropColumn("dbo.Di", "desfundo");
            DropColumn("dbo.Di", "desptrans1");
            DropColumn("dbo.Di", "desptrans2");
            DropColumn("dbo.Di", "desptrans3");
            DropColumn("dbo.Di", "despdestinof");
            DropColumn("dbo.Di", "desmeiotransp");
            DropColumn("dbo.Di", "desblegal");
            DropColumn("dbo.Di", "txDireito");
            DropColumn("dbo.Di", "tximpcons");
            DropColumn("dbo.Di", "txsobretx");
            DropColumn("dbo.Di", "txiva");
            DropColumn("dbo.Di", "tipodu");
            DropColumn("dbo.Di", "refinterna");
            DropColumn("dbo.Di", "tdistrib");
            DropColumn("dbo.Di", "PDireitos");
            DropColumn("dbo.Di", "Pimpcons");
            DropColumn("dbo.Di", "Psobretx");
            DropColumn("dbo.Di", "Piva");
            DropColumn("dbo.Di", "zeros");
            DropColumn("dbo.Di", "repfinanc");
            DropColumn("dbo.Di", "Autorproj");
            DropColumn("dbo.Di", "Autorcsta");
            DropColumn("dbo.Di", "odisplegal");
            DropColumn("dbo.Di", "displegal");
            DropColumn("dbo.Di", "benef");
            DropColumn("dbo.Di", "ArtGerais");
            DropColumn("dbo.Di", "tipoagenc");
            DropColumn("dbo.Di", "moznumber");
            DropColumn("dbo.Di", "tpdescmercad");
            DropColumn("dbo.Di", "tpcodmercad");
            DropColumn("dbo.Di", "pemb");
            DropColumn("dbo.Di", "adjud");
            DropColumn("dbo.Di", "datadjud");
            DropColumn("dbo.Di", "facc1stamp");
            DropColumn("dbo.Di", "facc2stamp");
            DropColumn("dbo.Di", "ndeclara");
            DropColumn("dbo.Di", "totpeso");
            DropColumn("dbo.Di", "totvolume");
            DropColumn("dbo.Di", "ano");
            DropColumn("dbo.Di", "dEntrada");
            DropColumn("dbo.Di", "dCheckin");
            DropColumn("dbo.Di", "dPagamento");
            DropColumn("dbo.Di", "dExamin");
            DropColumn("dbo.Di", "dVerific");
            DropColumn("dbo.Di", "dPronto");
            DropColumn("dbo.Di", "cifusd");
            DropColumn("dbo.Di", "cambiousd");
            DropColumn("dbo.Di", "DataFecho");
            DropColumn("dbo.Di", "calcfrete");
            DropColumn("dbo.Di", "calcseguro");
            DropColumn("dbo.Di", "inactivo");
            DropColumn("dbo.Di", "reserva");
            DropColumn("dbo.Di", "tipodoc");
            DropColumn("dbo.Di", "lant");
            DropColumn("dbo.Di", "lact");
            DropColumn("dbo.Di", "lreal");
            DropColumn("dbo.Di", "ldata");
            DropColumn("dbo.Di", "tipoentida");
            DropColumn("dbo.Di", "zona");
            DropColumn("dbo.Di", "ncont");
            DropColumn("dbo.Di", "codzona");
            DropColumn("dbo.Di", "fleitura");
            DropColumn("dbo.Di", "estabno");
            DropColumn("dbo.Di", "estabnome");
            DropColumn("dbo.Di", "Morada");
            DropColumn("dbo.Di", "Telefone");
            DropColumn("dbo.Di", "fax");
            DropColumn("dbo.Di", "nuit");
            DropColumn("dbo.Di", "email");
            DropColumn("dbo.Di", "optintro");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Di", "optintro", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "email", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "nuit", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "fax", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Telefone", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Morada", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "estabnome", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "estabno", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "fleitura", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "codzona", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "ncont", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "zona", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "tipoentida", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "ldata", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "lreal", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "lact", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "lant", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "tipodoc", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "reserva", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "inactivo", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "calcseguro", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "calcfrete", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "DataFecho", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "cambiousd", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "cifusd", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "dPronto", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "dVerific", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "dExamin", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "dPagamento", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "dCheckin", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "dEntrada", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "ano", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "totvolume", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "totpeso", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "ndeclara", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "facc2stamp", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "facc1stamp", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "datadjud", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "adjud", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "pemb", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "tpcodmercad", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "tpdescmercad", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "moznumber", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "tipoagenc", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "ArtGerais", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "benef", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "displegal", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "odisplegal", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Autorcsta", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Autorproj", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "repfinanc", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "zeros", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "Piva", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "Psobretx", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "Pimpcons", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "PDireitos", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "tdistrib", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "refinterna", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "tipodu", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "txiva", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "txsobretx", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "tximpcons", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "txDireito", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "desblegal", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desmeiotransp", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "despdestinof", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desptrans3", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desptrans2", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desptrans1", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desfundo", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desmetpagam", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "descodentreg", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "deslocdescarg", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "despdestino1", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "despembarque", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desfrnteira", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desregime", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "desestancia", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Proprietario", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Locmercador", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "blegal", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "isiva", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "issobretx", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "isimpcons", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "isdireito", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "datisencao", c => c.DateTime(nullable: false));
            AddColumn("dbo.Di", "nisencao", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "reflicenc", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "refprocur", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "refcambial", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "ntims", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "outras", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "pbruto", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "numselo", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "ptransp3", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "ptransp2", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "ptransp1", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "outrinfo", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "regarmaz", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "prevarmaz", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "fundo", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "metpagament", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "condentreg", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "locdescarg", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "nacional", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "paisdest", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "formpagadc", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "metaval", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "refdeclara", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "prdestino", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "sgarant", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "mgarant", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "ngarant", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "portdest", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "nrcontpag", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "pembarque", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "nvolumes", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "nregtransp", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "doctransp", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "manifesto", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "regime", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "estancia", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "duitems", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "dusequenc", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            AddColumn("dbo.Di", "Orc", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "Opcao1Other", c => c.String(nullable: false, maxLength: 80));
            AddColumn("dbo.Di", "Usaaprova", c => c.Boolean(nullable: false));
            AddColumn("dbo.Di", "codturno", c => c.Decimal(nullable: false, precision: 9, scale: 0));
            DropColumn("dbo.Di", "Desccodtz2");
            DropColumn("dbo.Di", "Codtz2");
        }
    }
}
