namespace DMZ.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addaparam : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.A_param",
                c => new
                    {
                        a_paramstamp = c.String(nullable: false, maxLength: 80),
                        qmc = c.String(nullable: false, maxLength: 80),
                        qmcdathora = c.DateTime(nullable: false),
                        qma = c.String(nullable: false, maxLength: 80),
                        qmadathora = c.DateTime(nullable: false),
                        ftmax = c.Decimal(nullable: false, precision: 9, scale: 0),
                        rfmax = c.Decimal(nullable: false, precision: 9, scale: 0),
                        despmax = c.Decimal(nullable: false, precision: 9, scale: 0),
                        dumax = c.Decimal(nullable: false, precision: 9, scale: 0),
                        rdcodtesoura = c.Decimal(nullable: false, precision: 9, scale: 0),
                        rdcontatesoura = c.String(nullable: false, maxLength: 80),
                        rdalttesoura = c.Boolean(nullable: false),
                        rccodtesoura = c.Decimal(nullable: false, precision: 9, scale: 0),
                        rccontatesoura = c.String(nullable: false, maxLength: 80),
                        rcalttesoura = c.Boolean(nullable: false),
                        rpcodtesoura = c.Decimal(nullable: false, precision: 9, scale: 0),
                        rpcontatesoura = c.String(nullable: false, maxLength: 80),
                        rpalttesoura = c.Boolean(nullable: false),
                        pgcodtesoura = c.Decimal(nullable: false, precision: 9, scale: 0),
                        pgcontatesoura = c.String(nullable: false, maxLength: 80),
                        pgalttesoura = c.Boolean(nullable: false),
                        ftaberto = c.Boolean(nullable: false),
                        separador = c.String(nullable: false, maxLength: 80),
                        ponto = c.String(nullable: false, maxLength: 80),
                        AVMAX = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ivcodentr = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ivdescentr = c.String(nullable: false, maxLength: 80),
                        ivcodsai = c.Decimal(nullable: false, precision: 9, scale: 0),
                        ivdescsai = c.String(nullable: false, maxLength: 80),
                        dseparador = c.String(nullable: false, maxLength: 80),
                        UsaPosRest = c.Boolean(nullable: false),
                        UsaPosQtt = c.Boolean(nullable: false),
                        MaskPosQtt = c.String(nullable: false, maxLength: 80),
                        MaskPosValor = c.String(nullable: false, maxLength: 80),
                        motivoiva = c.String(nullable: false, maxLength: 80),
                        cpextcccl = c.String(nullable: false, maxLength: 80),
                        cpextccfn = c.String(nullable: false, maxLength: 80),
                        cprd = c.String(nullable: false, maxLength: 80),
                        cprdf = c.String(nullable: false, maxLength: 80),
                        cplitsdocs = c.String(nullable: false, maxLength: 80),
                        cpmvtcc = c.String(nullable: false, maxLength: 80),
                        motivoivaeng = c.String(nullable: false, maxLength: 80),
                        usadi = c.Boolean(nullable: false),
                        usafact = c.Boolean(nullable: false),
                        usafacc = c.Boolean(nullable: false),
                        smtpserver = c.String(nullable: false, maxLength: 80),
                        smtpport = c.Decimal(nullable: false, precision: 9, scale: 0),
                        outgoingemail = c.String(nullable: false, maxLength: 80),
                        outgoingpassword = c.String(nullable: false, maxLength: 80),
                        destinationemail = c.String(nullable: false, maxLength: 80),
                        subj = c.String(nullable: false, maxLength: 80),
                        emailtext = c.String(nullable: false, maxLength: 80),
                        tipobase = c.Decimal(nullable: false, precision: 9, scale: 0),
                        formapag = c.String(nullable: false, maxLength: 80),
                        codtiposgs = c.Decimal(nullable: false, precision: 9, scale: 0),
                        desctiposgs = c.String(nullable: false, maxLength: 80),
                        codsgs = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descsgs = c.String(nullable: false, maxLength: 80),
                        SMTPServerp = c.String(nullable: false, maxLength: 80),
                        SMTPPortp = c.Decimal(nullable: false, precision: 9, scale: 0),
                        outGoingEmailp = c.String(nullable: false, maxLength: 80),
                        outGoingPasswordp = c.String(nullable: false, maxLength: 80),
                        destinationEmailp = c.String(nullable: false, maxLength: 80),
                        subjp = c.String(nullable: false, maxLength: 80),
                        emailTextp = c.String(nullable: false, maxLength: 80),
                        pathponto = c.String(nullable: false, maxLength: 80),
                        usaanexo = c.Boolean(nullable: false),
                        temailgest = c.Decimal(nullable: false, precision: 9, scale: 0),
                        temailpess = c.Decimal(nullable: false, precision: 9, scale: 0),
                        contacc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        fncpgc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        clpgc = c.Decimal(nullable: false, precision: 9, scale: 0),
                        grupo = c.String(nullable: false, maxLength: 80),
                        marca = c.String(nullable: false, maxLength: 80),
                        submarca = c.String(nullable: false, maxLength: 80),
                        nopend = c.Boolean(nullable: false),
                        codtzpos = c.Decimal(nullable: false, precision: 9, scale: 0),
                        contastesourapos = c.String(nullable: false, maxLength: 80),
                        comissao = c.Decimal(nullable: false, precision: 9, scale: 0),
                        qttsoma = c.Boolean(nullable: false),
                        gointro = c.Boolean(nullable: false),
                        noaltpreco = c.Boolean(nullable: false),
                        askremline = c.Boolean(nullable: false),
                        refauto = c.Boolean(nullable: false),
                        exprefauto = c.String(nullable: false, maxLength: 80),
                        extuser = c.String(nullable: false, maxLength: 80),
                        extpassw = c.String(nullable: false, maxLength: 80),
                        extdatabase = c.String(nullable: false, maxLength: 80),
                        extinstance = c.String(nullable: false, maxLength: 80),
                        ShowCapBarras = c.Boolean(nullable: false),
                        bdimagens = c.String(nullable: false, maxLength: 80),
                        percSeguro = c.Decimal(nullable: false, precision: 9, scale: 0),
                        percFrete = c.Decimal(nullable: false, precision: 9, scale: 0),
                        valormin = c.Decimal(nullable: false, precision: 9, scale: 0),
                        valormin2 = c.Decimal(nullable: false, precision: 9, scale: 0),
                        tabhonor = c.Boolean(nullable: false),
                        naoresumo = c.Boolean(nullable: false),
                        ivaagencia = c.Boolean(nullable: false),
                        PastaScan = c.String(nullable: false, maxLength: 80),
                        tipoimg = c.String(nullable: false, maxLength: 80),
                        usaexternalbd = c.Boolean(nullable: false),
                        usaestab = c.Boolean(nullable: false),
                        usacomerc = c.Boolean(nullable: false),
                        ano = c.Decimal(nullable: false, precision: 9, scale: 0),
                        autointcl = c.Boolean(nullable: false),
                        diarioTrf = c.String(nullable: false, maxLength: 80),
                        noDiTrf = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nDocContTrf = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descDocTrf = c.String(nullable: false, maxLength: 80),
                        diarioDp = c.String(nullable: false, maxLength: 80),
                        noDiDp = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nDocContDp = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descDocDp = c.String(nullable: false, maxLength: 80),
                        diarioMvt = c.String(nullable: false, maxLength: 80),
                        noDiMvt = c.Decimal(nullable: false, precision: 9, scale: 0),
                        nDocContMvt = c.Decimal(nullable: false, precision: 9, scale: 0),
                        descDocMvt = c.String(nullable: false, maxLength: 80),
                        autointfnc = c.Boolean(nullable: false),
                        usames = c.Boolean(nullable: false),
                        contmascara = c.String(nullable: false, maxLength: 80),
                        autointeg = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.a_paramstamp);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.A_param");
        }
    }
}
