// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class upprod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upprod));
        
        string IMigrationMetadata.Id
        {
            get { return "201902221501041_upprod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
