// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updparam130921 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updparam130921));
        
        string IMigrationMetadata.Id
        {
            get { return "202109222238394_updparam130921"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
