// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Updfactl03092021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updfactl03092021));
        
        string IMigrationMetadata.Id
        {
            get { return "202109031329460_Updfactl03092021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
