// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updStstamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updStstamp));
        
        string IMigrationMetadata.Id
        {
            get { return "202111041723069_updStstamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
