// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class alterst22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterst22));
        
        string IMigrationMetadata.Id
        {
            get { return "202203160806146_alterst22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
