// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PedescExcluiProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PedescExcluiProc));
        
        string IMigrationMetadata.Id
        {
            get { return "202208221256227_PedescExcluiProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
