// <auto-generated />
namespace DMZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ADICONACAMPO2CAIXAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADICONACAMPO2CAIXAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202309131652055_ADICONACAMPO2CAIXAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
